use crate::country_code::CountryCode;

impl CountryCode {
    // Check if the country has DST
    pub fn has_dst(&self) -> bool {
        match self {
            // Countries observing DST (true)
            // Europe (most EU/EEA countries observe DST, typically March to October)
            CountryCode::AUT => true, // Austria
            CountryCode::BEL => true, // Belgium
            CountryCode::BGR => true, // Bulgaria
            CountryCode::HRV => true, // Croatia
            CountryCode::CYP => true, // Cyprus
            CountryCode::CZE => true, // Czech Republic
            CountryCode::DNK => true, // Denmark
            CountryCode::EST => true, // Estonia
            CountryCode::FIN => true, // Finland
            CountryCode::FRA => true, // France
            CountryCode::DEU => true, // Germany
            CountryCode::GRC => true, // Greece
            CountryCode::HUN => true, // Hungary
            CountryCode::IRL => true, // Ireland
            CountryCode::ITA => true, // Italy
            CountryCode::LVA => true, // Latvia
            CountryCode::LTU => true, // Lithuania
            CountryCode::LUX => true, // Luxembourg
            CountryCode::MLT => true, // Malta
            CountryCode::NLD => true, // Netherlands
            CountryCode::POL => true, // Poland
            CountryCode::PRT => true, // Portugal
            CountryCode::ROU => true, // Romania
            CountryCode::SVK => true, // Slovakia
            CountryCode::SVN => true, // Slovenia
            CountryCode::ESP => true, // Spain
            CountryCode::SWE => true, // Sweden
            CountryCode::GBR => true, // United Kingdom
            CountryCode::NOR => true, // Norway (EEA)
            CountryCode::CHE => true, // Switzerland (follows EU DST)
            // North America
            CountryCode::USA => true, // United States (except Hawaii, most of Arizona)
            CountryCode::CAN => true, // Canada (except Yukon, most of Saskatchewan)
            CountryCode::CUB => true, // Cuba
            CountryCode::HTI => true, // Haiti
            CountryCode::MEX => true, // Mexico (only certain border cities, e.g., Tijuana)
            // South America
            CountryCode::CHL => true, // Chile (except Aysén, Magallanes)
            CountryCode::PRY => true, // Paraguay
            // Oceania
            CountryCode::AUS => true, // Australia (NSW, VIC, SA, TAS, ACT only)
            CountryCode::NZL => true, // New Zealand
            // Middle East and Africa
            CountryCode::EGY => true, // Egypt (reintroduced 2023)
            CountryCode::ISR => true, // Israel
            CountryCode::LBN => true, // Lebanon
            CountryCode::MAR => true, // Morocco (effectively permanent DST, except Ramadan)
            CountryCode::SYR => true, // Syria
            CountryCode::GRL => true, // Greenland (follows EU DST)

            // Countries not observing DST (false)
            // Europe
            CountryCode::ARM => false, // Armenia
            CountryCode::AZE => false, // Azerbaijan
            CountryCode::BLR => false, // Belarus
            CountryCode::GEO => false, // Georgia
            CountryCode::ISL => false, // Iceland
            CountryCode::RUS => false, // Russia (abolished 2014)
            CountryCode::TUR => false, // Turkey (abolished 2016)
            // Asia
            CountryCode::AFG => false, // Afghanistan
            CountryCode::BHR => false, // Bahrain
            CountryCode::BGD => false, // Bangladesh
            CountryCode::BTN => false, // Bhutan
            CountryCode::BRN => false, // Brunei
            CountryCode::KHM => false, // Cambodia
            CountryCode::CHN => false, // China
            CountryCode::IND => false, // India
            CountryCode::IDN => false, // Indonesia
            CountryCode::IRN => false, // Iran (abolished 2022)
            CountryCode::IRQ => false, // Iraq
            CountryCode::JPN => false, // Japan
            CountryCode::JOR => false, // Jordan
            CountryCode::KAZ => false, // Kazakhstan
            CountryCode::KWT => false, // Kuwait
            CountryCode::KGZ => false, // Kyrgyzstan
            CountryCode::LAO => false, // Laos
            CountryCode::MYS => false, // Malaysia
            CountryCode::MDV => false, // Maldives
            CountryCode::MNG => false, // Mongolia
            CountryCode::MMR => false, // Myanmar
            CountryCode::NPL => false, // Nepal
            CountryCode::OMN => false, // Oman
            CountryCode::PAK => false, // Pakistan
            CountryCode::PHL => false, // Philippines
            CountryCode::QAT => false, // Qatar
            CountryCode::SAU => false, // Saudi Arabia
            CountryCode::SGP => false, // Singapore
            CountryCode::KOR => false, // South Korea
            CountryCode::LKA => false, // Sri Lanka
            CountryCode::TWN => false, // Taiwan
            CountryCode::THA => false, // Thailand
            CountryCode::TLS => false, // Timor-Leste
            CountryCode::ARE => false, // United Arab Emirates
            CountryCode::UZB => false, // Uzbekistan
            CountryCode::VNM => false, // Vietnam
            // Africa
            CountryCode::DZA => false, // Algeria
            CountryCode::AGO => false, // Angola
            CountryCode::BEN => false, // Benin
            CountryCode::BWA => false, // Botswana
            CountryCode::BFA => false, // Burkina Faso
            CountryCode::BDI => false, // Burundi
            CountryCode::CMR => false, // Cameroon
            CountryCode::CAF => false, // Central African Republic
            CountryCode::TCD => false, // Chad
            CountryCode::COD => false, // DR Congo
            CountryCode::COG => false, // Congo
            CountryCode::CIV => false, // Côte d'Ivoire
            CountryCode::DJI => false, // Djibouti
            CountryCode::ERI => false, // Eritrea
            CountryCode::ETH => false, // Ethiopia
            CountryCode::GAB => false, // Gabon
            CountryCode::GMB => false, // Gambia
            CountryCode::GHA => false, // Ghana
            CountryCode::GIN => false, // Guinea
            CountryCode::KEN => false, // Kenya
            CountryCode::LSO => false, // Lesotho
            CountryCode::LBR => false, // Liberia
            CountryCode::LBY => false, // Libya
            CountryCode::MDG => false, // Madagascar
            CountryCode::MWI => false, // Malawi
            CountryCode::MLI => false, // Mali
            CountryCode::MRT => false, // Mauritania
            CountryCode::MOZ => false, // Mozambique
            CountryCode::NAM => false, // Namibia (abolished 2017)
            CountryCode::NER => false, // Niger
            CountryCode::NGA => false, // Nigeria
            CountryCode::RWA => false, // Rwanda
            CountryCode::SEN => false, // Senegal
            CountryCode::SLE => false, // Sierra Leone
            CountryCode::SOM => false, // Somalia
            CountryCode::ZAF => false, // South Africa
            CountryCode::SSD => false, // South Sudan
            CountryCode::SDN => false, // Sudan
            CountryCode::TGO => false, // Togo
            CountryCode::TUN => false, // Tunisia
            CountryCode::UGA => false, // Uganda
            CountryCode::ZMB => false, // Zambia
            CountryCode::ZWE => false, // Zimbabwe
            // South America
            CountryCode::ARG => false, // Argentina
            CountryCode::BOL => false, // Bolivia
            CountryCode::BRA => false, // Brazil (abolished 2019)
            CountryCode::COL => false, // Colombia
            CountryCode::ECU => false, // Ecuador
            CountryCode::GUY => false, // Guyana
            CountryCode::PER => false, // Peru
            CountryCode::SUR => false, // Suriname
            CountryCode::URY => false, // Uruguay (abolished 2015)
            CountryCode::VEN => false, // Venezuela
            // Oceania
            CountryCode::FJI => false, // Fiji
            CountryCode::PNG => false, // Papua New Guinea
            CountryCode::WSM => false, // Samoa
            CountryCode::VUT => false, // Vanuatu
            // Caribbean and Other
            CountryCode::ATG => false, // Antigua and Barbuda
            CountryCode::BHS => false, // Bahamas
            CountryCode::BRB => false, // Barbados
            CountryCode::BLZ => false, // Belize
            CountryCode::DMA => false, // Dominica
            CountryCode::GRD => false, // Grenada
            CountryCode::GTM => false, // Guatemala
            CountryCode::HND => false, // Honduras
            CountryCode::JAM => false, // Jamaica
            CountryCode::NIC => false, // Nicaragua
            CountryCode::PAN => false, // Panama
            CountryCode::KNA => false, // Saint Kitts and Nevis
            CountryCode::LCA => false, // Saint Lucia
            CountryCode::VCT => false, // Saint Vincent and the Grenadines
            CountryCode::TTO => false, // Trinidad and Tobago
            CountryCode::ESH => false, // Western Sahara
            CountryCode::YEM => false, // Yemen
            CountryCode::XKX => false, // Kosovo
            CountryCode::BMU => false, // Bermuda
            CountryCode::PCN => false, // Pitcairn
            CountryCode::TKL => false, // Tokelau
            CountryCode::TUV => false, // Tuvalu
            CountryCode::WLF => false, // Wallis and Futuna
            CountryCode::VAT => false, // Vatican City
            CountryCode::ALA => false, // Åland Islands
            CountryCode::ALB => false, // Albania
            CountryCode::ASM => false, // American Samoa
            CountryCode::AND => false, // Andorra
            CountryCode::AIA => false, // Anguilla
            CountryCode::ATA => false, // Antarctica
            CountryCode::ABW => false, // Aruba
            CountryCode::BES => false, // Bonaire, Sint Eustatius and Saba
            CountryCode::BIH => false, // Bosnia and Herzegovina
            CountryCode::BVT => false, // Bouvet Island
            CountryCode::IOT => false, // British Indian Ocean Territory
            CountryCode::VGB => false, // British Virgin Islands
            CountryCode::CPV => false, // Cape Verde
            CountryCode::CYM => false, // Cayman Islands
            CountryCode::CXR => false, // Christmas Island
            CountryCode::CCK => false, // Cocos (Keeling) Islands
            CountryCode::COM => false, // Comoros
            CountryCode::COK => false, // Cook Islands
            CountryCode::CRI => false, // Costa Rica
            CountryCode::CUW => false, // Curaçao
            CountryCode::DOM => false, // Dominican Republic
            CountryCode::SLV => false, // El Salvador
            CountryCode::GNQ => false, // Equatorial Guinea
            CountryCode::FLK => false, // Falkland Islands
            CountryCode::FRO => false, // Faroe Islands
            CountryCode::GUF => false, // French Guiana
            CountryCode::PYF => false, // French Polynesia
            CountryCode::ATF => false, // French Southern Territories
            CountryCode::GIB => false, // Gibraltar
            CountryCode::GLP => false, // Guadeloupe
            CountryCode::GUM => false, // Guam
            CountryCode::GGY => false, // Guernsey
            CountryCode::GNB => false, // Guinea-Bissau
            CountryCode::HMD => false, // Heard Island and McDonald Islands
            CountryCode::HKG => false, // Hong Kong
            CountryCode::IMN => false, // Isle of Man
            CountryCode::JEY => false, // Jersey
            CountryCode::KIR => false, // Kiribati
            CountryCode::PRK => false, // North Korea
            CountryCode::LIE => false, // Liechtenstein
            CountryCode::MAC => false, // Macao
            CountryCode::MKD => false, // North Macedonia
            CountryCode::MHL => false, // Marshall Islands
            CountryCode::MTQ => false, // Martinique
            CountryCode::MUS => false, // Mauritius
            CountryCode::MYT => false, // Mayotte
            CountryCode::FSM => false, // Micronesia
            CountryCode::MDA => false, // Moldova
            CountryCode::MCO => false, // Monaco
            CountryCode::MNE => false, // Montenegro
            CountryCode::MSR => false, // Montserrat
            CountryCode::NRU => false, // Nauru
            CountryCode::NCL => false, // New Caledonia
            CountryCode::NIU => false, // Niue
            CountryCode::NFK => false, // Norfolk Island
            CountryCode::MNP => false, // Northern Mariana Islands
            CountryCode::PLW => false, // Palau
            CountryCode::PSE => false, // Palestine
            CountryCode::PRI => false, // Puerto Rico
            CountryCode::REU => false, // Réunion
            CountryCode::BLM => false, // Saint Barthélemy
            CountryCode::SHN => false, // Saint Helena, Ascension and Tristan da Cunha
            CountryCode::MAF => false, // Saint Martin (French part)
            CountryCode::SPM => false, // Saint Pierre and Miquelon
            CountryCode::SMR => false, // San Marino
            CountryCode::STP => false, // Sao Tome and Principe
            CountryCode::SRB => false, // Serbia
            CountryCode::SYC => false, // Seychelles
            CountryCode::SXM => false, // Sint Maarten (Dutch part)
            CountryCode::SLB => false, // Solomon Islands
            CountryCode::SGS => false, // South Georgia and the South Sandwich Islands
            CountryCode::SJM => false, // Svalbard and Jan Mayen
            CountryCode::SWZ => false, // Eswatini
            CountryCode::TJK => false, // Tajikistan
            CountryCode::TZA => false, // Tanzania
            CountryCode::TKM => false, // Turkmenistan
            CountryCode::TCA => false, // Turks and Caicos Islands
            CountryCode::VIR => false, // U.S. Virgin Islands
            CountryCode::UKR => false, // Ukraine
            CountryCode::UMI => false, // United States Minor Outlying Islands
            CountryCode::TON => false, // Tonga
        }
    }
}
