use crate::time_zones::{
    IanaAfrica, IanaAmerica, IanaAntarctica, IanaArctic, IanaAsia, IanaAtlantic, IanaAustralia,
    IanaEurope, IanaIndian, IanaPacific, IanaTimeZone,
};

impl IanaTimeZone {
    // Returns utc offset in minutes at day saving time
    pub fn to_dst_offset_in_minutes(&self) -> i32 {
        let result = match self {
            IanaTimeZone::Europe(city) => match city {
                // Europe (most observe DST in August)
                IanaEurope::Amsterdam => 120, // UTC+02:00, DST active (Mar 30–Oct 26, 2025)
                IanaEurope::Andorra => 120,   // UTC+02:00, DST active (Mar 30–Oct 26, 2025)
                IanaEurope::Astrakhan => 240, // UTC+04:00, no DST
                IanaEurope::Athens => 180,    // UTC+03:00, DST active (Mar 30–Oct 26, 2025)
                IanaEurope::Belgrade => 120,  // UTC+02:00, DST active (Mar 30–Oct 26, 2025)
                IanaEurope::Berlin => 120,    // UTC+02:00, DST active (Mar 30–Oct 26, 2025)
                IanaEurope::Bratislava => 120, // UTC+02:00, DST active (Mar 30–Oct 26, 2025)
                IanaEurope::Brussels => 120,  // UTC+02:00, DST active (Mar 30–Oct 26, 2025)
                IanaEurope::Bucharest => 180, // UTC+03:00, DST active (Mar 30–Oct 26, 2025)
                IanaEurope::Budapest => 120,  // UTC+02:00, DST active (Mar 30–Oct 26, 2025)
                IanaEurope::Busingen => 120,  // UTC+02:00, DST active (Mar 30–Oct 26, 2025)
                IanaEurope::Chisinau => 180,  // UTC+03:00, DST active (Mar 30–Oct 26, 2025)
                IanaEurope::Copenhagen => 120, // UTC+02:00, DST active (Mar 30–Oct 26, 2025)
                IanaEurope::Dublin => 60,     // UTC+01:00, DST active (Mar 30–Oct 26, 2025)
                IanaEurope::Gibraltar => 120, // UTC+02:00, DST active (Mar 30–Oct 26, 2025)
                IanaEurope::Guernsey => 60,   // UTC+01:00, DST active (Mar 30–Oct 26, 2025)
                IanaEurope::Helsinki => 180,  // UTC+03:00, DST active (Mar 30–Oct 26, 2025)
                IanaEurope::IsleOfMan => 60,  // UTC+01:00, DST active (Mar 30–Oct 26, 2025)
                IanaEurope::Istanbul => 180,  // UTC+03:00, no DST
                IanaEurope::Jersey => 60,     // UTC+01:00, DST active (Mar 30–Oct 26, 2025)
                IanaEurope::Kaliningrad => 120, // UTC+02:00, no DST
                IanaEurope::Kirov => 180,     // UTC+03:00, no DST
                IanaEurope::Kyiv => 180,      // UTC+03:00, DST active (Mar 30–Oct 26, 2025)
                IanaEurope::Lisbon => 60,     // UTC+01:00, DST active (Mar 30–Oct 26, 2025)
                IanaEurope::Ljubljana => 120, // UTC+02:00, DST active (Mar 30–Oct 26, 2025)
                IanaEurope::London => 60,     // UTC+01:00, DST active (Mar 30–Oct 26, 2025)
                IanaEurope::Luxembourg => 120, // UTC+02:00, DST active (Mar 30–Oct 26, 2025)
                IanaEurope::Madrid => 120,    // UTC+02:00, DST active (Mar 30–Oct 26, 2025)
                IanaEurope::Malta => 120,     // UTC+02:00, DST active (Mar 30–Oct 26, 2025)
                IanaEurope::Mariehamn => 180, // UTC+03:00, DST active (Mar 30–Oct 26, 2025)
                IanaEurope::Minsk => 180,     // UTC+03:00, no DST
                IanaEurope::Monaco => 120,    // UTC+02:00, DST active (Mar 30–Oct 26, 2025)
                IanaEurope::Moscow => 180,    // UTC+03:00, no DST
                IanaEurope::Oslo => 120,      // UTC+02:00, DST active (Mar 30–Oct 26, 2025)
                IanaEurope::Paris => 120,     // UTC+02:00, DST active (Mar 30–Oct 26, 2025)
                IanaEurope::Podgorica => 120, // UTC+02:00, DST active (Mar 30–Oct 26, 2025)
                IanaEurope::Prague => 120,    // UTC+02:00, DST active (Mar 30–Oct 26, 2025)
                IanaEurope::Riga => 180,      // UTC+03:00, DST active (Mar 30–Oct 26, 2025)
                IanaEurope::Rome => 120,      // UTC+02:00, DST active (Mar 30–Oct 26, 2025)
                IanaEurope::Samara => 240,    // UTC+04:00, no DST
                IanaEurope::SanMarino => 120, // UTC+02:00, DST active (Mar 30–Oct 26, 2025)
                IanaEurope::Sarajevo => 120,  // UTC+02:00, DST active (Mar 30–Oct 26, 2025)
                IanaEurope::Saratov => 240,   // UTC+04:00, no DST
                IanaEurope::Simferopol => 180, // UTC+03:00, no DST
                IanaEurope::Skopje => 120,    // UTC+02:00, DST active (Mar 30–Oct 26, 2025)
                IanaEurope::Sofia => 180,     // UTC+03:00, DST active (Mar 30–Oct 26, 2025)
                IanaEurope::Stockholm => 120, // UTC+02:00, DST active (Mar 30–Oct 26, 2025)
                IanaEurope::Tallinn => 180,   // UTC+03:00, DST active (Mar 30–Oct 26, 2025)
                IanaEurope::Tirane => 120,    // UTC+02:00, DST active (Mar 30–Oct 26, 2025)
                IanaEurope::Ulyanovsk => 240, // UTC+04:00, no DST
                IanaEurope::Vaduz => 120,     // UTC+02:00, DST active (Mar 30–Oct 26, 2025)
                IanaEurope::Vatican => 120,   // UTC+02:00, DST active (Mar 30–Oct 26, 2025)
                IanaEurope::Vienna => 120,    // UTC+02:00, DST active (Mar 30–Oct 26, 2025)
                IanaEurope::Vilnius => 180,   // UTC+03:00, DST active (Mar 30–Oct 26, 2025)
                IanaEurope::Volgograd => 180, // UTC+03:00, no DST
                IanaEurope::Warsaw => 120,    // UTC+02:00, DST active (Mar 30–Oct 26, 2025)
                IanaEurope::Zagreb => 120,    // UTC+02:00, DST active (Mar 30–Oct 26, 2025)
                IanaEurope::Zurich => 120,    // UTC+02:00, DST active (Mar 30–Oct 26, 2025)
                IanaEurope::Nicosia => 180,   // UTC+03:00, DST active (Mar 30–Oct 26, 2025)
            },
            IanaTimeZone::Africa(city) => match city {
                IanaAfrica::Abidjan => 0,
                IanaAfrica::Accra => 0,
                IanaAfrica::AddisAbaba => 180,
                IanaAfrica::Algiers => 60,
                IanaAfrica::Asmara => 180,
                IanaAfrica::Bamako => 0,
                IanaAfrica::Bangui => 60,
                IanaAfrica::Banjul => 0,
                IanaAfrica::Bissau => 0,
                IanaAfrica::Blantyre => 120,
                IanaAfrica::Brazzaville => 60,
                IanaAfrica::Bujumbura => 120,
                IanaAfrica::Cairo => 180,
                IanaAfrica::Casablanca => 60,
                IanaAfrica::Conakry => 0,
                IanaAfrica::Dakar => 0,
                IanaAfrica::DarEsSalaam => 180,
                IanaAfrica::Djibouti => 180,
                IanaAfrica::Douala => 60,
                IanaAfrica::ElAaiun => 60,
                IanaAfrica::Freetown => 0,
                IanaAfrica::Gaborone => 120,
                IanaAfrica::Harare => 120,
                IanaAfrica::Juba => 120,
                IanaAfrica::Johannesburg => 120,
                IanaAfrica::Kampala => 180,
                IanaAfrica::Khartoum => 120,
                IanaAfrica::Kigali => 120,
                IanaAfrica::Kinshasa => 60,
                IanaAfrica::Lagos => 60,
                IanaAfrica::Libreville => 60,
                IanaAfrica::Lome => 0,
                IanaAfrica::Luanda => 60,
                IanaAfrica::Lusaka => 120,
                IanaAfrica::Malabo => 60,
                IanaAfrica::Maputo => 120,
                IanaAfrica::Maseru => 120,
                IanaAfrica::Mbabane => 120,
                IanaAfrica::Mogadishu => 180,
                IanaAfrica::Monrovia => 0,
                IanaAfrica::Nairobi => 180,
                IanaAfrica::Ndjamena => 60,
                IanaAfrica::Niamey => 60,
                IanaAfrica::Nouakchott => 0,
                IanaAfrica::PortoNovo => 60,
                IanaAfrica::SaoTome => 0,
                IanaAfrica::Tripoli => 120,
                IanaAfrica::Tunis => 60,
                IanaAfrica::Windhoek => 120,
                IanaAfrica::Antananarivo => 180,
                IanaAfrica::Ceuta => 120,
                IanaAfrica::Jamestown => 0,
                IanaAfrica::Lubumbashi => 120,
                IanaAfrica::Mamoudzou => 180,
                IanaAfrica::PortLouis => 240,
                IanaAfrica::Ouagadougou => 0,
            },
            IanaTimeZone::Asia(city) => match city {
                IanaAsia::Aden => 180,
                IanaAsia::Almaty => 300,
                IanaAsia::Amman => 180,
                IanaAsia::Ashgabat => 300,
                IanaAsia::Baghdad => 180,
                IanaAsia::Bahrain => 180,
                IanaAsia::Baku => 240,
                IanaAsia::Bangkok => 420,
                IanaAsia::Beirut => 180,
                IanaAsia::Bishkek => 360,
                IanaAsia::Colombo => 330,
                IanaAsia::Damascus => 180,
                IanaAsia::Dhaka => 360,
                IanaAsia::Dubai => 240,
                IanaAsia::Dushanbe => 300,
                IanaAsia::Gaza => 180,
                IanaAsia::Hovd => 420,
                IanaAsia::Irkutsk => 480,
                IanaAsia::Jakarta => 420,
                IanaAsia::Jayapura => 540,
                IanaAsia::Jerusalem => 180,
                IanaAsia::Kabul => 270,
                IanaAsia::Kamchatka => 720,
                IanaAsia::Karachi => 300,
                IanaAsia::Kathmandu => 345,
                IanaAsia::KualaLumpur => 480,
                IanaAsia::Macao => 480,
                IanaAsia::Magadan => 660,
                IanaAsia::Makassar => 480,
                IanaAsia::Manila => 480,
                IanaAsia::Muscat => 240,
                IanaAsia::Nicosia => 180,
                IanaAsia::Omsk => 360,
                IanaAsia::Pyongyang => 540,
                IanaAsia::Qatar => 180,
                IanaAsia::Riyadh => 180,
                IanaAsia::Seoul => 540,
                IanaAsia::Shanghai => 480,
                IanaAsia::Singapore => 480,
                IanaAsia::Taipei => 480,
                IanaAsia::Tashkent => 300,
                IanaAsia::Tbilisi => 240,
                IanaAsia::Tehran => 210,
                IanaAsia::Thimphu => 360,
                IanaAsia::Tokyo => 540,
                IanaAsia::Ulaanbaatar => 480,
                IanaAsia::Urumqi => 360,
                IanaAsia::Vladivostok => 600,
                IanaAsia::Yakutsk => 540,
                IanaAsia::Yekaterinburg => 300,
                IanaAsia::Yerevan => 240,
                IanaAsia::Krasnoyarsk => 420,   // UTC+07:00, no DST
                IanaAsia::Aqtau => 300,         // UTC+05:00, no DST
                IanaAsia::Aqtobe => 300,        // UTC+05:00, no DST
                IanaAsia::Atyrau => 300,        // UTC+05:00, no DST
                IanaAsia::Chita => 540,         // UTC+09:00, no DST
                IanaAsia::Choibalsan => 480,    // UTC+08:00, no DST
                IanaAsia::Dili => 540,          // UTC+09:00, no DST
                IanaAsia::Hebron => 180,        // UTC+03:00, DST active (Mar 30–Oct 26, 2025)
                IanaAsia::HongKong => 480,      // UTC+08:00, no DST
                IanaAsia::Khandyga => 540,      // UTC+09:00, no DST
                IanaAsia::Kyzylorda => 300,     // UTC+05:00, no DST
                IanaAsia::Novokuznetsk => 420,  // UTC+07:00, no DST
                IanaAsia::Novosibirsk => 420,   // UTC+07:00, no DST
                IanaAsia::Pontianak => 420,     // UTC+07:00, no DST
                IanaAsia::Qostanay => 360,      // UTC+06:00, no DST
                IanaAsia::Qyzylorda => 300,     // UTC+05:00, no DST
                IanaAsia::Sakhalin => 660,      // UTC+11:00, no DST
                IanaAsia::Srednekolymsk => 660, // UTC+11:00, no DST
                IanaAsia::Tomsk => 420,         // UTC+07:00, no DST
                IanaAsia::Kolkata => 330,       // UTC+05:30, no DST
                IanaAsia::Brunei => 480,        // UTC+08:00, no DST
                IanaAsia::Kuwait => 180,        // UTC+03:00, DST active (Mar 30–Oct 26, 2025)
                IanaAsia::PhnomPenh => 420,     // UTC+07:00, no DST
                IanaAsia::Vientiane => 420,     // UTC+07:00, no DST
                IanaAsia::HoChiMinh => 420,     // UTC+07:00, no DST
                IanaAsia::Yangon => 390,        // UTC+06:30, no DST
                IanaAsia::Chongqing => 480,     // UTC+08:00, no DST
                IanaAsia::Harbin => 480,        // UTC+08:00, no DST
                IanaAsia::Kashgar => 360,       // UTC+06:00, no DST
                IanaAsia::UlanBator => 480,     // UTC+08:00, no DST
                IanaAsia::Barnaul => 420,       // UTC+07:00, no DST
                IanaAsia::Anadyr => 720,        // UTC+12:00, no DST
                IanaAsia::Famagusta => 180,     // UTC+03:00, DST active
                IanaAsia::Kuching => 480,       // UTC+08:00, no DST
                IanaAsia::Macau => 480,         // UTC+08:00, no DST
                IanaAsia::Oral => 300,          // UTC+05:00, no DST
                IanaAsia::Samarkand => 300,     // UTC+05:00, no DST
                IanaAsia::UstNera => 600,       // UTC+10:00, no DST
            },
            IanaTimeZone::America(city) => match city {
                IanaAmerica::Adak => -540,
                IanaAmerica::Anchorage => -480,
                IanaAmerica::Anguilla => -240,
                IanaAmerica::Antigua => -240,
                IanaAmerica::Argentina(_) => -180,
                IanaAmerica::Aruba => -240,
                IanaAmerica::Asuncion => -240,
                IanaAmerica::Barbados => -240,
                IanaAmerica::Belize => -360,
                IanaAmerica::Bogota => -300,
                IanaAmerica::Cancun => -300,
                IanaAmerica::Caracas => -240,
                IanaAmerica::Cayenne => -180,
                IanaAmerica::Cayman => -300,
                IanaAmerica::Chicago => -300,
                IanaAmerica::CostaRica => -360,
                IanaAmerica::Curacao => -240,
                IanaAmerica::Denver => -360,
                IanaAmerica::Dominica => -240,
                IanaAmerica::Edmonton => -360,
                IanaAmerica::ElSalvador => -360,
                IanaAmerica::GrandTurk => -240,
                IanaAmerica::Grenada => -240,
                IanaAmerica::Guadeloupe => -240,
                IanaAmerica::Guatemala => -360,
                IanaAmerica::Guayaquil => -300,
                IanaAmerica::Guyana => -240,
                IanaAmerica::Halifax => -180,
                IanaAmerica::Havana => -240,
                IanaAmerica::Honolulu => -600,
                IanaAmerica::Jamaica => -300,
                IanaAmerica::Kralendijk => -240,
                IanaAmerica::LaPaz => -240,
                IanaAmerica::Lima => -300,
                IanaAmerica::LosAngeles => -420,
                IanaAmerica::Managua => -360,
                IanaAmerica::Manaus => -240,
                IanaAmerica::Marigot => -240,
                IanaAmerica::Martinique => -240,
                IanaAmerica::Mazatlan => -360, // UTC-06:00, DST active (Mar 9–Nov 2, 2025)
                IanaAmerica::MexicoCity => -300, // UTC-05:00, DST active (Apr 6–Oct 26, 2025)
                IanaAmerica::Miquelon => -120,
                IanaAmerica::Montevideo => -180,
                IanaAmerica::Nassau => -240,
                IanaAmerica::NewYork => -240,
                IanaAmerica::Nuuk => -120,
                IanaAmerica::Paramaribo => -180,
                IanaAmerica::Phoenix => -420, // UTC-07:00, no DST (Arizona doesn't observe DST)
                IanaAmerica::Pitcairn => -480,
                IanaAmerica::PortOfSpain => -240,
                IanaAmerica::PortAuPrince => -240,
                IanaAmerica::PuertoRico => -240,
                IanaAmerica::PuntaArenas => -180,
                IanaAmerica::Regina => -360,
                IanaAmerica::RioBranco => -300,
                IanaAmerica::SantoDomingo => -240,
                IanaAmerica::Santiago => -180,
                IanaAmerica::SaoPaulo => -180,
                IanaAmerica::StBarthelemy => -240,
                IanaAmerica::StJohns => -150,
                IanaAmerica::StKitts => -240,
                IanaAmerica::StLucia => -240,
                IanaAmerica::StThomas => -240,
                IanaAmerica::StVincent => -240,
                IanaAmerica::Tegucigalpa => -360,
                IanaAmerica::Toronto => -240,
                IanaAmerica::Tortola => -240,
                IanaAmerica::Vancouver => -420,
                IanaAmerica::Winnipeg => -300,
                IanaAmerica::LowerPrinces => -240,
                IanaAmerica::Tijuana => -420,
                IanaAmerica::Montserrat => -240,
                IanaAmerica::Noronha => -120,
                IanaAmerica::Panama => -300,
            },
            IanaTimeZone::Antarctica(city) => match city {
                IanaAntarctica::McMurdo => 780,        // UTC+13:00, DST active (Sep 28–Apr 5, 2025)
                IanaAntarctica::Palmer => -180,        // UTC-03:00, no DST
                IanaAntarctica::Rothera => -60,        // UTC-01:00, no DST
                IanaAntarctica::Syowa => 180,          // UTC+03:00, no DST
                IanaAntarctica::Troll => 0,            // UTC+00:00, no DST
                IanaAntarctica::Vostok => 360,         // UTC+06:00, no DST
                IanaAntarctica::SouthPole => 0,        // UTC+00:00, no DST
                IanaAntarctica::Casey => 600,          // UTC+10:00, no DST
                IanaAntarctica::Davis => 600,          // UTC+10:00, no DST
                IanaAntarctica::DumontDUrville => 600, // UTC+10:00, no DST
                IanaAntarctica::Macquarie => 600,      // UTC+10:00, no DST
                IanaAntarctica::Mawson => 600,         // UTC+10:00, no DST
            },
            IanaTimeZone::Arctic(city) => match city {
                IanaArctic::Longyearbyen => 120, // UTC+02:00, DST active (Mar 30–Oct 26, 2025)
            },
            IanaTimeZone::Atlantic(city) => match city {
                IanaAtlantic::Azores => 0,      // UTC+00:00, DST active (Mar 30–Oct 26, 2025)
                IanaAtlantic::Bermuda => -180,  // UTC-03:00, DST active (Mar 9–Nov 2, 2025)
                IanaAtlantic::CapeVerde => -60, // UTC-01:00, no DST
                IanaAtlantic::Faeroe => 60,     // UTC+01:00, DST active (Mar 30–Oct 26, 2025)
                IanaAtlantic::Reykjavik => 0,   // UTC+00:00, no DST
                IanaAtlantic::SouthGeorgia => -120, // UTC-02:00, no DST
                IanaAtlantic::Stanley => -180,  // UTC-03:00, no DST
                IanaAtlantic::StHelena => 0,    // UTC+00:00, no DST
                IanaAtlantic::Canary => 0,      // UTC+00:00, no DST
                IanaAtlantic::Madeira => 0,     // UTC+00:00, no DST
                IanaAtlantic::Faroe => 0,       // UTC+00:00, no DST
            },
            IanaTimeZone::Australia(city) => match city {
                IanaAustralia::Adelaide => 630, // UTC+10:30, DST active (Oct 5–Apr 6, 2025)
                IanaAustralia::Brisbane => 600, // UTC+10:00, no DST
                IanaAustralia::Darwin => 570,   // UTC+09:30, no DST
                IanaAustralia::Ecula => 525,    // UTC+08:45, no DST
                IanaAustralia::Hobart => 660,   // UTC+11:00, DST active (Oct 5–Apr 6, 2025)
                IanaAustralia::Lindeman => 600, // UTC+10:00, no DST
                IanaAustralia::LordHowe => 660, // UTC+11:00, DST active (Oct 5–Apr 6, 2025)
                IanaAustralia::Melbourne => 660, // UTC+11:00, DST active (Oct 5–Apr 6, 2025)
                IanaAustralia::Perth => 480,    // UTC+08:00, no DST
                IanaAustralia::Sydney => 660,   // UTC+11:00, DST active (Oct 5–Apr 6, 2025)
            },
            IanaTimeZone::Indian(city) => match city {
                IanaIndian::Antananarivo => 180, // UTC+03:00, no DST
                IanaIndian::Chagos => 360,       // UTC+06:00, no DST
                IanaIndian::Christmas => 420,    // UTC+07:00, no DST
                IanaIndian::Cocos => 390,        // UTC+06:30, no DST
                IanaIndian::Comoro => 180,       // UTC+03:00, no DST
                IanaIndian::Kerguelen => 300,    // UTC+05:00, no DST
                IanaIndian::Mahe => 240,         // UTC+04:00, no DST
                IanaIndian::Maldives => 300,     // UTC+05:00, no DST
                IanaIndian::Mauritius => 240,    // UTC+04:00, no DST
                IanaIndian::Mayotte => 180,      // UTC+03:00, no DST
                IanaIndian::Reunion => 240,      // UTC+04:00, no DST
            },
            IanaTimeZone::Pacific(city) => match city {
                IanaPacific::Apia => 780,        // UTC+13:00, DST active (Sep 28–Apr 5, 2025)
                IanaPacific::Auckland => 780,    // UTC+13:00, DST active (Sep 28–Apr 5, 2025)
                IanaPacific::Baker => -720,      // UTC-12:00, no DST
                IanaPacific::Efate => 660,       // UTC+11:00, no DST
                IanaPacific::Fakaofo => 780,     // UTC+13:00, no DST
                IanaPacific::Fiji => 720,        // UTC+12:00, no DST
                IanaPacific::Funafuti => 720,    // UTC+12:00, no DST
                IanaPacific::Guam => 600,        // UTC+10:00, no DST
                IanaPacific::Guadalcanal => 660, // UTC+11:00, no DST
                IanaPacific::Honolulu => -600,   // UTC-10:00, no DST
                IanaPacific::Kiritimati => 840,  // UTC+14:00, no DST
                IanaPacific::Majuro => 720,      // UTC+12:00, no DST
                IanaPacific::Midway => -660,     // UTC-11:00, no DST
                IanaPacific::Nauru => 720,       // UTC+12:00, no DST
                IanaPacific::Niue => -660,       // UTC-11:00, no DST
                IanaPacific::Norfolk => 660,     // UTC+11:00, no DST
                IanaPacific::Noumea => 660,      // UTC+11:00, no DST
                IanaPacific::Palau => 540,       // UTC+09:00, no DST
                IanaPacific::Pitcairn => -480,   // UTC-08:00, no DST
                IanaPacific::Pohnpei => 660,     // UTC+11:00, no DST
                IanaPacific::PortMoresby => 600, // UTC+10:00, no DST
                IanaPacific::Rarotonga => -600,  // UTC-10:00, no DST
                IanaPacific::Saipan => 600,      // UTC+10:00, no DST
                IanaPacific::Tahiti => -600,     // UTC-10:00, no DST
                IanaPacific::Tarawa => 720,      // UTC+12:00, no DST
                IanaPacific::Tongatapu => 780,   // UTC+13:00, no DST
                IanaPacific::Wallis => 720,      // UTC+12:00, no DST
                IanaPacific::PagoPago => -660,   // UTC-11:00, no DST
            },
        };

        result
    }
}
