use crate::country_code::CountryCode;

use super::*;

pub enum IanaCountry {
    Country(CountryCode),
    Arctic,
}

impl Into<IanaCountry> for CountryCode {
    fn into(self) -> IanaCountry {
        IanaCountry::Country(self)
    }
}

impl Into<CountryCode> for IanaTimeZone {
    fn into(self) -> CountryCode {
        let iana_country: IanaCountry = self.into();

        match iana_country {
            IanaCountry::Country(country) => country,
            IanaCountry::Arctic => panic!("Arctic is not a country to convert to country code"),
        }
    }
}

impl Into<IanaCountry> for IanaTimeZone {
    fn into(self) -> IanaCountry {
        match self {
            IanaTimeZone::Africa(country) => match country {
                IanaAfrica::Abidjan => CountryCode::CIV,
                IanaAfrica::Accra => CountryCode::GHA,
                IanaAfrica::AddisAbaba => CountryCode::ETH,
                IanaAfrica::Algiers => CountryCode::DZA,
                IanaAfrica::Antananarivo => CountryCode::MDG,
                IanaAfrica::Asmara => CountryCode::ERI,
                IanaAfrica::Bamako => CountryCode::MLI,
                IanaAfrica::Bangui => CountryCode::CAF,
                IanaAfrica::Banjul => CountryCode::GMB,
                IanaAfrica::Bissau => CountryCode::GNB,
                IanaAfrica::Blantyre => CountryCode::MWI,
                IanaAfrica::Brazzaville => CountryCode::COG,
                IanaAfrica::Bujumbura => CountryCode::BDI,
                IanaAfrica::Ceuta => CountryCode::ESP,
                IanaAfrica::Cairo => CountryCode::EGY,
                IanaAfrica::Casablanca => CountryCode::MAR,
                IanaAfrica::Conakry => CountryCode::GIN,
                IanaAfrica::Dakar => CountryCode::SEN,
                IanaAfrica::DarEsSalaam => CountryCode::TZA,
                IanaAfrica::Djibouti => CountryCode::DJI,
                IanaAfrica::Douala => CountryCode::CMR,
                IanaAfrica::ElAaiun => CountryCode::ESH,
                IanaAfrica::Freetown => CountryCode::SLE,
                IanaAfrica::Gaborone => CountryCode::BWA,
                IanaAfrica::Jamestown => CountryCode::SHN,
                IanaAfrica::Harare => CountryCode::ZWE,
                IanaAfrica::Juba => CountryCode::SSD,
                IanaAfrica::Johannesburg => CountryCode::ZAF,
                IanaAfrica::Kampala => CountryCode::UGA,
                IanaAfrica::Khartoum => CountryCode::SDN,
                IanaAfrica::Kigali => CountryCode::RWA,
                IanaAfrica::Kinshasa => CountryCode::COD,
                IanaAfrica::Lubumbashi => CountryCode::COD,
                IanaAfrica::Lagos => CountryCode::NGA,
                IanaAfrica::Libreville => CountryCode::GAB,
                IanaAfrica::Lome => CountryCode::TGO,
                IanaAfrica::Luanda => CountryCode::AGO,
                IanaAfrica::Lusaka => CountryCode::ZMB,
                IanaAfrica::Mamoudzou => CountryCode::MYT,
                IanaAfrica::Malabo => CountryCode::GNQ,
                IanaAfrica::Maputo => CountryCode::MOZ,
                IanaAfrica::Maseru => CountryCode::LSO,
                IanaAfrica::Mbabane => CountryCode::SWZ,
                IanaAfrica::Mogadishu => CountryCode::SOM,
                IanaAfrica::Monrovia => CountryCode::LBR,
                IanaAfrica::Nairobi => CountryCode::KEN,
                IanaAfrica::Ndjamena => CountryCode::TCD,
                IanaAfrica::Niamey => CountryCode::NER,
                IanaAfrica::Nouakchott => CountryCode::MRT,
                IanaAfrica::PortLouis => CountryCode::MUS,
                IanaAfrica::PortoNovo => CountryCode::BEN,
                IanaAfrica::SaoTome => CountryCode::STP,
                IanaAfrica::Ouagadougou => CountryCode::BFA,
                IanaAfrica::Tripoli => CountryCode::LBY,
                IanaAfrica::Tunis => CountryCode::TUN,
                IanaAfrica::Windhoek => CountryCode::NAM,
            }
            .into(),
            IanaTimeZone::America(country) => match country {
                IanaAmerica::Adak => CountryCode::USA,
                IanaAmerica::Anchorage => CountryCode::USA,
                IanaAmerica::Anguilla => CountryCode::AIA,
                IanaAmerica::Antigua => CountryCode::ATG,
                IanaAmerica::Argentina(_) => CountryCode::ARG,
                IanaAmerica::Aruba => CountryCode::ABW,
                IanaAmerica::Asuncion => CountryCode::PRY,
                IanaAmerica::Barbados => CountryCode::BRB,
                IanaAmerica::Belize => CountryCode::BLZ,
                IanaAmerica::Bogota => CountryCode::COL,
                IanaAmerica::Cancun => CountryCode::MEX,
                IanaAmerica::Caracas => CountryCode::VEN,
                IanaAmerica::Cayenne => CountryCode::GUF,
                IanaAmerica::Cayman => CountryCode::CYM,
                IanaAmerica::Chicago => CountryCode::USA,
                IanaAmerica::CostaRica => CountryCode::CRI,
                IanaAmerica::Curacao => CountryCode::CUW,
                IanaAmerica::Denver => CountryCode::USA,
                IanaAmerica::Dominica => CountryCode::DMA,
                IanaAmerica::Edmonton => CountryCode::CAN,
                IanaAmerica::ElSalvador => CountryCode::SLV,
                IanaAmerica::GrandTurk => CountryCode::TCA,
                IanaAmerica::Grenada => CountryCode::GRD,
                IanaAmerica::Guadeloupe => CountryCode::GLP,
                IanaAmerica::Guatemala => CountryCode::GTM,
                IanaAmerica::Guayaquil => CountryCode::ECU,
                IanaAmerica::Guyana => CountryCode::GUY,
                IanaAmerica::Halifax => CountryCode::CAN,
                IanaAmerica::Havana => CountryCode::CUB,
                IanaAmerica::Honolulu => CountryCode::USA,
                IanaAmerica::Jamaica => CountryCode::JAM,
                IanaAmerica::Kralendijk => CountryCode::BES,
                IanaAmerica::LaPaz => CountryCode::BOL,
                IanaAmerica::Lima => CountryCode::PER,
                IanaAmerica::LosAngeles => CountryCode::USA,
                IanaAmerica::Managua => CountryCode::NIC,
                IanaAmerica::Manaus => CountryCode::BRA,
                IanaAmerica::Marigot => CountryCode::MAF,
                IanaAmerica::Martinique => CountryCode::MTQ,
                IanaAmerica::Montserrat => CountryCode::MSR,
                IanaAmerica::Mazatlan => CountryCode::MEX,
                IanaAmerica::MexicoCity => CountryCode::MEX,
                IanaAmerica::Noronha => CountryCode::BRA,
                IanaAmerica::Miquelon => CountryCode::SPM,
                IanaAmerica::Montevideo => CountryCode::URY,
                IanaAmerica::Nassau => CountryCode::BHS,
                IanaAmerica::NewYork => CountryCode::USA,
                IanaAmerica::Panama => CountryCode::PAN,
                IanaAmerica::Nuuk => CountryCode::GRL,
                IanaAmerica::Paramaribo => CountryCode::SUR,
                IanaAmerica::Phoenix => CountryCode::USA,
                IanaAmerica::Pitcairn => CountryCode::PCN,
                IanaAmerica::LowerPrinces => CountryCode::SXM,
                IanaAmerica::PortOfSpain => CountryCode::TTO,
                IanaAmerica::PortAuPrince => CountryCode::HTI,
                IanaAmerica::PuertoRico => CountryCode::PRI,
                IanaAmerica::PuntaArenas => CountryCode::CHL,
                IanaAmerica::Regina => CountryCode::CAN,
                IanaAmerica::RioBranco => CountryCode::BRA,
                IanaAmerica::Tijuana => CountryCode::MEX,
                IanaAmerica::SantoDomingo => CountryCode::DOM,
                IanaAmerica::Santiago => CountryCode::CHL,
                IanaAmerica::SaoPaulo => CountryCode::BRA,
                IanaAmerica::StBarthelemy => CountryCode::BLM,
                IanaAmerica::StJohns => CountryCode::CAN,
                IanaAmerica::StKitts => CountryCode::KNA,
                IanaAmerica::StLucia => CountryCode::LCA,
                IanaAmerica::StThomas => CountryCode::VIR,
                IanaAmerica::StVincent => CountryCode::VCT,
                IanaAmerica::Tegucigalpa => CountryCode::HND,
                IanaAmerica::Toronto => CountryCode::CAN,
                IanaAmerica::Tortola => CountryCode::VGB,
                IanaAmerica::Vancouver => CountryCode::CAN,
                IanaAmerica::Winnipeg => CountryCode::CAN,
            }
            .into(),
            IanaTimeZone::Antarctica(_) => CountryCode::ATA.into(),
            IanaTimeZone::Asia(country) => match country {
                IanaAsia::Aden => CountryCode::YEM,
                IanaAsia::Almaty => CountryCode::KAZ,
                IanaAsia::Amman => CountryCode::JOR,
                IanaAsia::Anadyr => CountryCode::RUS,
                IanaAsia::Aqtau => CountryCode::KAZ,
                IanaAsia::Aqtobe => CountryCode::KAZ,
                IanaAsia::Ashgabat => CountryCode::TKM,
                IanaAsia::Atyrau => CountryCode::KAZ,
                IanaAsia::Baghdad => CountryCode::IRQ,
                IanaAsia::Bahrain => CountryCode::BHR,
                IanaAsia::Baku => CountryCode::AZE,
                IanaAsia::Bangkok => CountryCode::THA,
                IanaAsia::Barnaul => CountryCode::RUS,
                IanaAsia::Beirut => CountryCode::LBN,
                IanaAsia::Bishkek => CountryCode::KGZ,
                IanaAsia::Brunei => CountryCode::BRN,
                IanaAsia::Chita => CountryCode::RUS,
                IanaAsia::Choibalsan => CountryCode::MNG,
                IanaAsia::Colombo => CountryCode::LKA,
                IanaAsia::Damascus => CountryCode::SYR,
                IanaAsia::Dhaka => CountryCode::BGD,
                IanaAsia::Dili => CountryCode::TLS,
                IanaAsia::Dubai => CountryCode::ARE,
                IanaAsia::Dushanbe => CountryCode::TJK,
                IanaAsia::Famagusta => CountryCode::CYP,
                IanaAsia::Gaza => CountryCode::PSE,
                IanaAsia::Hebron => CountryCode::PSE,
                IanaAsia::HoChiMinh => CountryCode::VNM,
                IanaAsia::HongKong => CountryCode::HKG,
                IanaAsia::Hovd => CountryCode::MNG,
                IanaAsia::Irkutsk => CountryCode::RUS,
                IanaAsia::Jakarta => CountryCode::IDN,
                IanaAsia::Jayapura => CountryCode::IDN,
                IanaAsia::Jerusalem => CountryCode::ISR,
                IanaAsia::Kabul => CountryCode::AFG,
                IanaAsia::Kamchatka => CountryCode::RUS,
                IanaAsia::Karachi => CountryCode::PAK,
                IanaAsia::Kathmandu => CountryCode::NPL,
                IanaAsia::Khandyga => CountryCode::RUS,
                IanaAsia::Kolkata => CountryCode::IND,
                IanaAsia::Krasnoyarsk => CountryCode::RUS,
                IanaAsia::KualaLumpur => CountryCode::MYS,
                IanaAsia::Kuching => CountryCode::MYS,
                IanaAsia::Kuwait => CountryCode::KWT,
                IanaAsia::Macau => CountryCode::MAC,
                IanaAsia::Magadan => CountryCode::RUS,
                IanaAsia::Makassar => CountryCode::IDN,
                IanaAsia::Manila => CountryCode::PHL,
                IanaAsia::Muscat => CountryCode::OMN,
                IanaAsia::Nicosia => CountryCode::CYP,
                IanaAsia::Novokuznetsk => CountryCode::RUS,
                IanaAsia::Novosibirsk => CountryCode::RUS,
                IanaAsia::Omsk => CountryCode::RUS,
                IanaAsia::Oral => CountryCode::KAZ,
                IanaAsia::PhnomPenh => CountryCode::KHM,
                IanaAsia::Pontianak => CountryCode::IDN,
                IanaAsia::Pyongyang => CountryCode::PRK,
                IanaAsia::Qatar => CountryCode::QAT,
                IanaAsia::Qostanay => CountryCode::KAZ,
                IanaAsia::Riyadh => CountryCode::SAU,
                IanaAsia::Sakhalin => CountryCode::RUS,
                IanaAsia::Samarkand => CountryCode::UZB,
                IanaAsia::Seoul => CountryCode::KOR,
                IanaAsia::Shanghai => CountryCode::CHN,
                IanaAsia::Singapore => CountryCode::SGP,
                IanaAsia::Srednekolymsk => CountryCode::RUS,
                IanaAsia::Taipei => CountryCode::TWN,
                IanaAsia::Tashkent => CountryCode::UZB,
                IanaAsia::Tbilisi => CountryCode::GEO,
                IanaAsia::Tehran => CountryCode::IRN,
                IanaAsia::Thimphu => CountryCode::BTN,
                IanaAsia::Tokyo => CountryCode::JPN,
                IanaAsia::Tomsk => CountryCode::RUS,
                IanaAsia::Ulaanbaatar => CountryCode::MNG,
                IanaAsia::Urumqi => CountryCode::CHN,
                IanaAsia::UstNera => CountryCode::RUS,
                IanaAsia::Vientiane => CountryCode::LAO,
                IanaAsia::Vladivostok => CountryCode::RUS,
                IanaAsia::Yakutsk => CountryCode::RUS,
                IanaAsia::Yangon => CountryCode::MMR,
                IanaAsia::Yekaterinburg => CountryCode::RUS,
                IanaAsia::Yerevan => CountryCode::ARM,
                IanaAsia::Macao => CountryCode::MAC,
                IanaAsia::Kyzylorda => CountryCode::KAZ,
                IanaAsia::Qyzylorda => CountryCode::KAZ,
                IanaAsia::Chongqing => CountryCode::CHN,
                IanaAsia::Harbin => CountryCode::CHN,
                IanaAsia::Kashgar => CountryCode::CHN,
                IanaAsia::UlanBator => CountryCode::MNG,
            }
            .into(),
            IanaTimeZone::Atlantic(country) => match country {
                IanaAtlantic::Azores => CountryCode::PRT,
                IanaAtlantic::Bermuda => CountryCode::BMU,
                IanaAtlantic::Canary => CountryCode::ESP,
                IanaAtlantic::CapeVerde => CountryCode::CPV,
                IanaAtlantic::Faroe => CountryCode::FRO,
                IanaAtlantic::Madeira => CountryCode::PRT,
                IanaAtlantic::Reykjavik => CountryCode::ISL,
                IanaAtlantic::SouthGeorgia => CountryCode::SGS,
                IanaAtlantic::StHelena => CountryCode::SHN,
                IanaAtlantic::Stanley => CountryCode::FLK,
                IanaAtlantic::Faeroe => CountryCode::FRO,
            }
            .into(),
            IanaTimeZone::Australia(_) => CountryCode::AUS.into(),
            IanaTimeZone::Europe(country) => match country {
                IanaEurope::Amsterdam => CountryCode::NLD,
                IanaEurope::Andorra => CountryCode::AND,
                IanaEurope::Astrakhan => CountryCode::RUS,
                IanaEurope::Athens => CountryCode::GRC,
                IanaEurope::Belgrade => CountryCode::SRB,
                IanaEurope::Berlin => CountryCode::DEU,
                IanaEurope::Bratislava => CountryCode::SVK,
                IanaEurope::Brussels => CountryCode::BEL,
                IanaEurope::Bucharest => CountryCode::ROU,
                IanaEurope::Budapest => CountryCode::HUN,
                IanaEurope::Busingen => CountryCode::DEU,
                IanaEurope::Chisinau => CountryCode::MDA,
                IanaEurope::Copenhagen => CountryCode::DNK,
                IanaEurope::Dublin => CountryCode::IRL,
                IanaEurope::Gibraltar => CountryCode::GIB,
                IanaEurope::Guernsey => CountryCode::GGY,
                IanaEurope::Helsinki => CountryCode::FIN,
                IanaEurope::IsleOfMan => CountryCode::IMN,
                IanaEurope::Istanbul => CountryCode::TUR,
                IanaEurope::Jersey => CountryCode::JEY,
                IanaEurope::Kaliningrad => CountryCode::RUS,
                IanaEurope::Kirov => CountryCode::RUS,
                IanaEurope::Kyiv => CountryCode::UKR,
                IanaEurope::Lisbon => CountryCode::PRT,
                IanaEurope::Ljubljana => CountryCode::SVN,
                IanaEurope::London => CountryCode::GBR,
                IanaEurope::Luxembourg => CountryCode::LUX,
                IanaEurope::Madrid => CountryCode::ESP,
                IanaEurope::Malta => CountryCode::MLT,
                IanaEurope::Mariehamn => CountryCode::ALA,
                IanaEurope::Minsk => CountryCode::BLR,
                IanaEurope::Monaco => CountryCode::MCO,
                IanaEurope::Moscow => CountryCode::RUS,
                IanaEurope::Nicosia => CountryCode::CYP,
                IanaEurope::Oslo => CountryCode::NOR,
                IanaEurope::Paris => CountryCode::FRA,
                IanaEurope::Podgorica => CountryCode::MNE,
                IanaEurope::Prague => CountryCode::CZE,
                IanaEurope::Riga => CountryCode::LVA,
                IanaEurope::Rome => CountryCode::ITA,
                IanaEurope::Samara => CountryCode::RUS,
                IanaEurope::SanMarino => CountryCode::SMR,
                IanaEurope::Sarajevo => CountryCode::BIH,
                IanaEurope::Saratov => CountryCode::RUS,
                IanaEurope::Simferopol => CountryCode::UKR,
                IanaEurope::Skopje => CountryCode::MKD,
                IanaEurope::Sofia => CountryCode::BGR,
                IanaEurope::Stockholm => CountryCode::SWE,
                IanaEurope::Tallinn => CountryCode::EST,
                IanaEurope::Tirane => CountryCode::ALB,
                IanaEurope::Ulyanovsk => CountryCode::RUS,
                IanaEurope::Vaduz => CountryCode::LIE,
                IanaEurope::Vatican => CountryCode::VAT,
                IanaEurope::Vienna => CountryCode::AUT,
                IanaEurope::Vilnius => CountryCode::LTU,
                IanaEurope::Volgograd => CountryCode::RUS,
                IanaEurope::Warsaw => CountryCode::POL,
                IanaEurope::Zagreb => CountryCode::HRV,
                IanaEurope::Zurich => CountryCode::CHE,
            }
            .into(),
            IanaTimeZone::Indian(country) => match country {
                IanaIndian::Antananarivo => CountryCode::MDG,
                IanaIndian::Chagos => CountryCode::IOT,
                IanaIndian::Christmas => CountryCode::CXR,
                IanaIndian::Cocos => CountryCode::CCK,
                IanaIndian::Comoro => CountryCode::COM,
                IanaIndian::Kerguelen => CountryCode::ATF,
                IanaIndian::Mahe => CountryCode::SYC,
                IanaIndian::Maldives => CountryCode::MDV,
                IanaIndian::Mauritius => CountryCode::MUS,
                IanaIndian::Mayotte => CountryCode::MYT,
                IanaIndian::Reunion => CountryCode::REU,
            }
            .into(),
            IanaTimeZone::Pacific(country) => match country {
                IanaPacific::Apia => CountryCode::WSM,
                IanaPacific::Auckland => CountryCode::NZL,
                IanaPacific::Baker => CountryCode::UMI,
                IanaPacific::Efate => CountryCode::VUT,
                IanaPacific::Fakaofo => CountryCode::TKL,
                IanaPacific::Fiji => CountryCode::FJI,
                IanaPacific::Funafuti => CountryCode::TUV,
                IanaPacific::Guam => CountryCode::GUM,
                IanaPacific::Guadalcanal => CountryCode::SLB,
                IanaPacific::Honolulu => CountryCode::USA,
                IanaPacific::Kiritimati => CountryCode::KIR,
                IanaPacific::Majuro => CountryCode::MHL,
                IanaPacific::Midway => CountryCode::UMI,
                IanaPacific::Nauru => CountryCode::NRU,
                IanaPacific::Niue => CountryCode::NIU,
                IanaPacific::Norfolk => CountryCode::NFK,
                IanaPacific::Noumea => CountryCode::NCL,
                IanaPacific::Palau => CountryCode::PLW,
                IanaPacific::Pitcairn => CountryCode::PCN,
                IanaPacific::Pohnpei => CountryCode::FSM,
                IanaPacific::PortMoresby => CountryCode::PNG,
                IanaPacific::Rarotonga => CountryCode::COK,
                IanaPacific::Saipan => CountryCode::MNP,
                IanaPacific::Tahiti => CountryCode::PYF,
                IanaPacific::Tarawa => CountryCode::KIR,
                IanaPacific::Tongatapu => CountryCode::TON,
                IanaPacific::Wallis => CountryCode::WLF,
                IanaPacific::PagoPago => CountryCode::ASM,
            }
            .into(),
            IanaTimeZone::Arctic(_) => IanaCountry::Arctic,
        }
    }
}
