use crate::time_zones::{IanaCanada, IanaChile, IanaMexico, IanaTimeZone, IanaUS};

use super::*;

impl IanaTimeZone {
    // Returns utc offset in minutes at not day saving time
    pub fn to_no_dst_offset_in_minutes(&self) -> i32 {
        let result = match self {
            IanaTimeZone::Europe(city) => match city {
                IanaEurope::Amsterdam => 60,
                IanaEurope::Andorra => 60,
                IanaEurope::Astrakhan => 240,
                IanaEurope::Athens => 120,
                IanaEurope::Belgrade => 60,
                IanaEurope::Berlin => 60,
                IanaEurope::Bratislava => 60,
                IanaEurope::Brussels => 60,
                IanaEurope::Bucharest => 120,
                IanaEurope::Budapest => 60,
                IanaEurope::Busingen => 60,
                IanaEurope::Chisinau => 120,
                IanaEurope::Copenhagen => 60,
                IanaEurope::Dublin => 0,
                IanaEurope::Gibraltar => 60,
                IanaEurope::Guernsey => 0,
                IanaEurope::Helsinki => 120,
                IanaEurope::IsleOfMan => 0,
                IanaEurope::Istanbul => 180,
                IanaEurope::Jersey => 0,
                IanaEurope::Kaliningrad => 120,
                IanaEurope::Kirov => 180,
                IanaEurope::Kyiv => 120,
                IanaEurope::Lisbon => 0,
                IanaEurope::Ljubljana => 60,
                IanaEurope::London => 0,
                IanaEurope::Luxembourg => 60,
                IanaEurope::Madrid => 60,
                IanaEurope::Malta => 60,
                IanaEurope::Mariehamn => 120,
                IanaEurope::Minsk => 180,
                IanaEurope::Monaco => 60,
                IanaEurope::Moscow => 180,
                IanaEurope::Oslo => 60,
                IanaEurope::Paris => 60,
                IanaEurope::Podgorica => 60,
                IanaEurope::Prague => 60,
                IanaEurope::Riga => 120,
                IanaEurope::Rome => 60,
                IanaEurope::Samara => 240,
                IanaEurope::SanMarino => 60,
                IanaEurope::Sarajevo => 60,
                IanaEurope::Saratov => 240,
                IanaEurope::Simferopol => 180,
                IanaEurope::Skopje => 60,
                IanaEurope::Sofia => 120,
                IanaEurope::Stockholm => 60,
                IanaEurope::Tallinn => 120,
                IanaEurope::Tirane => 60,
                IanaEurope::Ulyanovsk => 240,
                IanaEurope::Vaduz => 60,
                IanaEurope::Vatican => 60,
                IanaEurope::Vienna => 60,
                IanaEurope::Vilnius => 120,
                IanaEurope::Volgograd => 180,
                IanaEurope::Warsaw => 60,
                IanaEurope::Zagreb => 60,
                IanaEurope::Zurich => 60,
                IanaEurope::Nicosia => 120,
                IanaEurope::Belfast => 0,
                IanaEurope::Tiraspol => 60,
                IanaEurope::Uzhgorod => 60,
                IanaEurope::Zaporozhye => 60,
            },
            IanaTimeZone::Africa(city) => match city {
                IanaAfrica::Abidjan => 0,
                IanaAfrica::Accra => 0,
                IanaAfrica::AddisAbaba => 180,
                IanaAfrica::Algiers => 60,
                IanaAfrica::Antananarivo => 180,
                IanaAfrica::Asmara => 180,
                IanaAfrica::Bamako => 0,
                IanaAfrica::Bangui => 60,
                IanaAfrica::Banjul => 0,
                IanaAfrica::Bissau => 0,
                IanaAfrica::Blantyre => 120,
                IanaAfrica::Brazzaville => 60,
                IanaAfrica::Bujumbura => 120,
                IanaAfrica::Ceuta => 60,
                IanaAfrica::Cairo => 120,
                IanaAfrica::Casablanca => 0,
                IanaAfrica::Conakry => 0,
                IanaAfrica::Dakar => 0,
                IanaAfrica::DarEsSalaam => 180,
                IanaAfrica::Djibouti => 180,
                IanaAfrica::Douala => 60,
                IanaAfrica::ElAaiun => 0,
                IanaAfrica::Freetown => 0,
                IanaAfrica::Gaborone => 120,
                IanaAfrica::Jamestown => 0,
                IanaAfrica::Harare => 120,
                IanaAfrica::Juba => 120,
                IanaAfrica::Johannesburg => 120,
                IanaAfrica::Kampala => 180,
                IanaAfrica::Khartoum => 120,
                IanaAfrica::Kigali => 120,
                IanaAfrica::Kinshasa => 60,
                IanaAfrica::Lubumbashi => 120,
                IanaAfrica::Lagos => 60,
                IanaAfrica::Libreville => 60,
                IanaAfrica::Lome => 0,
                IanaAfrica::Luanda => 60,
                IanaAfrica::Lusaka => 120,
                IanaAfrica::Mamoudzou => 180,
                IanaAfrica::Malabo => 60,
                IanaAfrica::Maputo => 120,
                IanaAfrica::Maseru => 120,
                IanaAfrica::Mbabane => 120,
                IanaAfrica::Mogadishu => 180,
                IanaAfrica::Monrovia => 0,
                IanaAfrica::Nairobi => 180,
                IanaAfrica::Ndjamena => 60,
                IanaAfrica::Niamey => 60,
                IanaAfrica::Nouakchott => 0,
                IanaAfrica::PortLouis => 240,
                IanaAfrica::PortoNovo => 60,
                IanaAfrica::SaoTome => 0,
                IanaAfrica::Tripoli => 120,
                IanaAfrica::Tunis => 60,
                IanaAfrica::Windhoek => 120,
                IanaAfrica::Ouagadougou => 0,
                IanaAfrica::Asmera => 0,
                IanaAfrica::Timbuktu => 0,
            },
            IanaTimeZone::Asia(city) => match city {
                IanaAsia::Aden => 180,
                IanaAsia::Almaty => 300,
                IanaAsia::Amman => 120,
                IanaAsia::Ashgabat => 300,
                IanaAsia::Baghdad => 180,
                IanaAsia::Bahrain => 180,
                IanaAsia::Baku => 240,
                IanaAsia::Bangkok => 420,
                IanaAsia::Beirut => 120,
                IanaAsia::Bishkek => 360,
                IanaAsia::Colombo => 330,
                IanaAsia::Damascus => 120,
                IanaAsia::Dhaka => 360,
                IanaAsia::Dubai => 240,
                IanaAsia::Dushanbe => 300,
                IanaAsia::Gaza => 120,
                IanaAsia::Hovd => 420,
                IanaAsia::Irkutsk => 480,
                IanaAsia::Jakarta => 420,
                IanaAsia::Jayapura => 540,
                IanaAsia::Jerusalem => 120,
                IanaAsia::Kabul => 270,
                IanaAsia::Kamchatka => 720,
                IanaAsia::Karachi => 300,
                IanaAsia::Kathmandu => 345,
                IanaAsia::KualaLumpur => 480,
                IanaAsia::Macao => 480,
                IanaAsia::Magadan => 660,
                IanaAsia::Makassar => 480,
                IanaAsia::Manila => 480,
                IanaAsia::Muscat => 240,
                IanaAsia::Nicosia => 120,
                IanaAsia::Omsk => 360,
                IanaAsia::Pyongyang => 540,
                IanaAsia::Qatar => 180,
                IanaAsia::Riyadh => 180,
                IanaAsia::Seoul => 540,
                IanaAsia::Shanghai => 480,
                IanaAsia::Singapore => 480,
                IanaAsia::Taipei => 480,
                IanaAsia::Tashkent => 300,
                IanaAsia::Tbilisi => 240,
                IanaAsia::Tehran => 210,
                IanaAsia::Thimphu => 360,
                IanaAsia::Tokyo => 540,
                IanaAsia::Ulaanbaatar => 480,
                IanaAsia::Urumqi => 360,
                IanaAsia::Vladivostok => 600,
                IanaAsia::Yakutsk => 540,
                IanaAsia::Yekaterinburg => 300,
                IanaAsia::Yerevan => 240,
                IanaAsia::Krasnoyarsk => 420,
                IanaAsia::Aqtau => 300,
                IanaAsia::Aqtobe => 300,
                IanaAsia::Atyrau => 300,
                IanaAsia::Chita => 540,
                IanaAsia::Choibalsan => 480,
                IanaAsia::Dili => 540,
                IanaAsia::Hebron => 180,
                IanaAsia::HongKong => 480,
                IanaAsia::Khandyga => 540,
                IanaAsia::Kyzylorda => 300,
                IanaAsia::Novokuznetsk => 420,
                IanaAsia::Novosibirsk => 420,
                IanaAsia::Pontianak => 420,
                IanaAsia::Qostanay => 360,
                IanaAsia::Qyzylorda => 300,
                IanaAsia::Sakhalin => 660,
                IanaAsia::Srednekolymsk => 660,
                IanaAsia::Tomsk => 420,
                IanaAsia::Kolkata => 330,
                IanaAsia::Brunei => 480,
                IanaAsia::PhnomPenh => 420,
                IanaAsia::Kuwait => 180,
                IanaAsia::Vientiane => 420,
                IanaAsia::HoChiMinh => 420,
                IanaAsia::Yangon => 390,
                IanaAsia::Chongqing => 480,
                IanaAsia::Harbin => 480,
                IanaAsia::Kashgar => 360,
                IanaAsia::UlanBator => 480,
                IanaAsia::Barnaul => 420,
                IanaAsia::Anadyr => 720,
                IanaAsia::Famagusta => 120,
                IanaAsia::Kuching => 480,
                IanaAsia::Macau => 480,
                IanaAsia::Oral => 300,
                IanaAsia::Samarkand => 300,
                IanaAsia::UstNera => 600,
                IanaAsia::Calcutta => 330, // UTC+5:30, no DST (same as Kolkata)
                IanaAsia::Chungking => 480, // UTC+08:00, no DST
                IanaAsia::Dacca => 360,    // UTC+06:00, no DST
                IanaAsia::Istanbul => 180, // UTC+03:00, no DST
                IanaAsia::TelAviv => 120,  // UTC+02:00, no DST
                IanaAsia::UjungPandang => 480, // UTC+08:00, no DST
                IanaAsia::Katmandu => 345, // UTC+05:45, no DST
                IanaAsia::Thimbu => 360,   // UTC+06:00, no DST
                IanaAsia::Rangoon => 390,  // UTC+06:30, no DST
                IanaAsia::Saigon => 420,   // UTC+07:00, no DST
            },
            IanaTimeZone::America(city) => match city {
                IanaAmerica::Adak => -600,
                IanaAmerica::Anchorage => -540,
                IanaAmerica::Anguilla => -240,
                IanaAmerica::Antigua => -240,
                IanaAmerica::Argentina(_) => -180,
                IanaAmerica::Aruba => -240,
                IanaAmerica::Asuncion => -240,
                IanaAmerica::Barbados => -240,
                IanaAmerica::Belize => -360,
                IanaAmerica::Bogota => -300,
                IanaAmerica::Cancun => -300,
                IanaAmerica::Caracas => -240,
                IanaAmerica::Cayenne => -180,
                IanaAmerica::Cayman => -300,
                IanaAmerica::Chicago => -360,
                IanaAmerica::CostaRica => -360,
                IanaAmerica::Curacao => -240,
                IanaAmerica::Denver => -420,
                IanaAmerica::Dominica => -240,
                IanaAmerica::Edmonton => -420,
                IanaAmerica::ElSalvador => -360,
                IanaAmerica::GrandTurk => -300,
                IanaAmerica::Grenada => -240,
                IanaAmerica::Guadeloupe => -240,
                IanaAmerica::Guatemala => -360,
                IanaAmerica::Guayaquil => -300,
                IanaAmerica::Guyana => -240,
                IanaAmerica::Halifax => -240,
                IanaAmerica::Havana => -300,
                IanaAmerica::Honolulu => -600,
                IanaAmerica::Jamaica => -300,
                IanaAmerica::Kralendijk => -240,
                IanaAmerica::LaPaz => -240,
                IanaAmerica::Lima => -300,
                IanaAmerica::LosAngeles => -480,
                IanaAmerica::Managua => -360,
                IanaAmerica::Manaus => -240,
                IanaAmerica::Marigot => -240,
                IanaAmerica::Martinique => -240,
                IanaAmerica::Mazatlan => -420,
                IanaAmerica::MexicoCity => -360,
                IanaAmerica::Miquelon => -180,
                IanaAmerica::Montevideo => -180,
                IanaAmerica::Montserrat => -240,
                IanaAmerica::Nassau => -240,
                IanaAmerica::NewYork => -300,
                IanaAmerica::Noronha => -120,
                IanaAmerica::Nuuk => -180,
                IanaAmerica::Paramaribo => -180,
                IanaAmerica::Panama => -300,
                IanaAmerica::Phoenix => -420,
                IanaAmerica::Pitcairn => -480,
                IanaAmerica::PortOfSpain => -240,
                IanaAmerica::PortAuPrince => -300,
                IanaAmerica::PuertoRico => -240,
                IanaAmerica::PuntaArenas => -180,
                IanaAmerica::Regina => -360,
                IanaAmerica::RioBranco => -300,
                IanaAmerica::SantoDomingo => -240,
                IanaAmerica::Santiago => -240,
                IanaAmerica::SaoPaulo => -180,
                IanaAmerica::StBarthelemy => -240,
                IanaAmerica::StJohns => -210,
                IanaAmerica::StKitts => -240,
                IanaAmerica::StLucia => -240,
                IanaAmerica::StThomas => -240,
                IanaAmerica::StVincent => -240,
                IanaAmerica::Tegucigalpa => -360,
                IanaAmerica::Toronto => -300,
                IanaAmerica::Tortola => -240,
                IanaAmerica::Vancouver => -480,
                IanaAmerica::Winnipeg => -360,
                IanaAmerica::LowerPrinces => -240,
                IanaAmerica::Tijuana => -480,
                IanaAmerica::Araguaina => -180,
                IanaAmerica::Atikokan => -300,
                IanaAmerica::Atka => -600,
                IanaAmerica::Bahia => -180,
                IanaAmerica::BahiaBanderas => -360,
                IanaAmerica::Belem => -180,
                IanaAmerica::BlancSablon => -240,
                IanaAmerica::BoaVista => -240,
                IanaAmerica::BuenosAires => -180,
                IanaAmerica::CambridgeBay => -420,
                IanaAmerica::CampoGrande => -240,
                IanaAmerica::Catamarca => -180,
                IanaAmerica::Chihuahua => -420,
                IanaAmerica::CiudadJuarez => -420,
                IanaAmerica::CoralHarbour => -300,
                IanaAmerica::Coyhaique => -180,
                IanaAmerica::Creston => -480,
                IanaAmerica::Cuiaba => -240,
                IanaAmerica::Cordoba => -180,
                IanaAmerica::Boise => -420,
                IanaAmerica::Danmarkshavn => 0,   // UTC+00:00, no DST
                IanaAmerica::Dawson => -480,      // UTC-08:00, no DST
                IanaAmerica::DawsonCreek => -420, // UTC-07:00, no DST
                IanaAmerica::Detroit => -300,     // UTC-05:00, no DST
                IanaAmerica::Eirunepe => -300,    // UTC-05:00, no DST
                IanaAmerica::Ensenada => -480,    // UTC-08:00, no DST
                IanaAmerica::FortNelson => -420,  // UTC-07:00, no DST
                IanaAmerica::FortWayne => -300,   // UTC-05:00, no DST
                IanaAmerica::Fortaleza => -180,   // UTC-03:00, no DST
                IanaAmerica::Hermosillo => -420,  // UTC-07:00, no DST
                IanaAmerica::GlaceBay => -240,    // UTC-04:00, no DST
                IanaAmerica::Godthab => -180,     // UTC-03:00, no DST
                IanaAmerica::GooseBay => -240,    // UTC-04:00, no DST
                IanaAmerica::Indiana(_) => -300,  // UTC-05:00, no DST
                IanaAmerica::Indianapolis => -300, // UTC-05:00, no DST
                IanaAmerica::Inuvik => -420,      // UTC-07:00, no DST
                IanaAmerica::Iqaluit => -300,     // UTC-05:00, no DST
                IanaAmerica::Juneau => -540,      // UTC-09:00, no DST
                IanaAmerica::Jujuy => -180,       // UTC-03:00, no DST
                IanaAmerica::KnoxIN => -300,      // UTC-05:00, no DST
                IanaAmerica::Louisville => -300,  // UTC-05:00, no DST
                IanaAmerica::Maceio => -180,      // UTC-03:00, no DST
                IanaAmerica::Matamoros => -360,   // UTC-06:00, no DST
                IanaAmerica::Mendoza => -180,     // UTC-03:00, no DST
                IanaAmerica::Menominee => -300,   // UTC-05:00, no DST
                IanaAmerica::Merida => -300,      // UTC-05:00, no DST
                IanaAmerica::Metlakatla => -540,  // UTC-09:00, no DST
                IanaAmerica::Moncton => -240,     // UTC-04:00, no DST
                IanaAmerica::Monterrey => -360,   // UTC-06:00, no DST
                IanaAmerica::Montreal => -300,    // UTC-05:00, no DST
                IanaAmerica::Nipigon => -300,     // UTC-05:00, no DST
                IanaAmerica::Nome => -540,        // UTC-09:00, no DST
                IanaAmerica::Ojinaga => -360,     // UTC-06:00, no DST
                IanaAmerica::Pangnirtung => -300, // UTC-05:00, no DST
                IanaAmerica::PortoAcre => -300,   // UTC-05:00, no DST
                IanaAmerica::PortoVelho => -240,  // UTC-04:00, no DST
                IanaAmerica::RainyRiver => -360,  // UTC-06:00, no DST
                IanaAmerica::RankinInlet => -360, // UTC-06:00, no DST
                IanaAmerica::Recife => -180,      // UTC-03:00, no DST
                IanaAmerica::Resolute => -360,    // UTC-06:00, no DST
                IanaAmerica::Rosario => -180,     // UTC-03:00, no DST
                IanaAmerica::SantaIsabel => -480, // UTC-08:00, no DST
                IanaAmerica::Santarem => -180,    // UTC-03:00, no DST
                IanaAmerica::Scoresbysund => -180, // UTC-03:00, no DST
                IanaAmerica::Shiprock => -420,    // UTC-07:00, no DST
                IanaAmerica::Sitka => -540,       // UTC-09:00, no DST
                IanaAmerica::SwiftCurrent => -360, // UTC-06:00, no DST
                IanaAmerica::Thule => -180,       // UTC-03:00, no DST
                IanaAmerica::ThunderBay => -300,  // UTC-05:00, no DST
                IanaAmerica::Virgin => -240,      // UTC-04:00, no DST
                IanaAmerica::Whitehorse => -420,  // UTC-07:00, no DST
                IanaAmerica::Yakutat => -540,     // UTC-09:00, no DST
                IanaAmerica::Yellowknife => -360, // UTC-06:00, no DST
                IanaAmerica::Kentucky(_) => -360, // UTC-06:00, no DST
                IanaAmerica::NorthDakota(_) => -360, // UTC-06:00, no DST
            },
            IanaTimeZone::Antarctica(city) => match city {
                IanaAntarctica::McMurdo => 720,
                IanaAntarctica::Palmer => -180,
                IanaAntarctica::Rothera => -60,
                IanaAntarctica::Syowa => 180,
                IanaAntarctica::Troll => 0,
                IanaAntarctica::Vostok => 360,
                IanaAntarctica::SouthPole => 0,
                IanaAntarctica::Casey => 600,
                IanaAntarctica::Davis => 600,
                IanaAntarctica::DumontDUrville => 600,
                IanaAntarctica::Macquarie => 600,
                IanaAntarctica::Mawson => 600,
            },
            IanaTimeZone::Arctic(city) => match city {
                IanaArctic::Longyearbyen => 60,
            },
            IanaTimeZone::Atlantic(city) => match city {
                IanaAtlantic::Azores => -60,
                IanaAtlantic::Bermuda => -240,
                IanaAtlantic::CapeVerde => -60,
                IanaAtlantic::Faeroe => 0,
                IanaAtlantic::Reykjavik => 0,
                IanaAtlantic::SouthGeorgia => -120,
                IanaAtlantic::Stanley => -180,
                IanaAtlantic::StHelena => 0,
                IanaAtlantic::Canary => 0,
                IanaAtlantic::Madeira => 0,
                IanaAtlantic::Faroe => 0,
                IanaAtlantic::JanMayen => 0, // UTC+00:00, no DST
            },
            IanaTimeZone::Australia(city) => match city {
                IanaAustralia::Adelaide => 570,
                IanaAustralia::Brisbane => 600,
                IanaAustralia::Darwin => 570,
                IanaAustralia::Eucla => 525,
                IanaAustralia::Hobart => 600,
                IanaAustralia::Lindeman => 600,
                IanaAustralia::LordHowe => 630,
                IanaAustralia::Melbourne => 600,
                IanaAustralia::Perth => 480,
                IanaAustralia::Sydney => 600,
                IanaAustralia::BrokenHill => 570,
                IanaAustralia::Canberra => 600,
                IanaAustralia::Currie => 600,
                IanaAustralia::LHI => 600,
                IanaAustralia::North => 570,
                IanaAustralia::NSW => 600,
                IanaAustralia::Queensland => 600,
                IanaAustralia::South => 570,
                IanaAustralia::Tasmania => 600,
                IanaAustralia::Victoria => 600,
                IanaAustralia::West => 480,
                IanaAustralia::Yancowinna => 570,
            },
            IanaTimeZone::Indian(city) => match city {
                IanaIndian::Antananarivo => 180,
                IanaIndian::Chagos => 360,
                IanaIndian::Christmas => 420,
                IanaIndian::Cocos => 390,
                IanaIndian::Comoro => 180,
                IanaIndian::Kerguelen => 300,
                IanaIndian::Mahe => 240,
                IanaIndian::Maldives => 300,
                IanaIndian::Mauritius => 240,
                IanaIndian::Mayotte => 180,
                IanaIndian::Reunion => 240,
            },
            IanaTimeZone::Brazil(city) => match city {
                IanaBrazil::Acre => -300,      // UTC-05:00, no DST
                IanaBrazil::DeNoronha => -120, // UTC-02:00, no DST
                IanaBrazil::East => -180,      // UTC-03:00, no DST
                IanaBrazil::West => -240,      // UTC-04:00, no DST
            },
            IanaTimeZone::Pacific(city) => match city {
                IanaPacific::Apia => 780,
                IanaPacific::Auckland => 720,
                IanaPacific::Baker => -720,
                IanaPacific::Efate => 660,
                IanaPacific::Fakaofo => 780,
                IanaPacific::Fiji => 720,
                IanaPacific::Funafuti => 720,
                IanaPacific::Guam => 600,
                IanaPacific::Guadalcanal => 660,
                IanaPacific::Honolulu => -600,
                IanaPacific::Kiritimati => 840,
                IanaPacific::Majuro => 720,
                IanaPacific::Midway => -660,
                IanaPacific::Nauru => 720,
                IanaPacific::Niue => -660,
                IanaPacific::Norfolk => 660,
                IanaPacific::Noumea => 660,
                IanaPacific::Palau => 540,
                IanaPacific::Pitcairn => -480,
                IanaPacific::Pohnpei => 660,
                IanaPacific::PortMoresby => 600,
                IanaPacific::Rarotonga => -600,
                IanaPacific::Saipan => 600,
                IanaPacific::Tahiti => -600,
                IanaPacific::Tarawa => 720,
                IanaPacific::Tongatapu => 780,
                IanaPacific::Wallis => 720,
                IanaPacific::PagoPago => -660,
                IanaPacific::Bougainville => 660,
                IanaPacific::Chatham => 780,
                IanaPacific::Chuuk => 600,
                IanaPacific::Easter => -360,
                IanaPacific::Enderbury => 780,
                IanaPacific::Galapagos => -360,
                IanaPacific::Gambier => -540,
                IanaPacific::Johnston => -600,
                IanaPacific::Kanton => 780,

                IanaPacific::Kosrae => 660,
                IanaPacific::Kwajalein => 720,

                IanaPacific::Marquesas => -570,

                IanaPacific::Samoa => 780,

                IanaPacific::Truk => 600,
                IanaPacific::Wake => 720,

                IanaPacific::Yap => 600,
            },
            IanaTimeZone::Canada(city) => match city {
                IanaCanada::Atlantic => -240,     // UTC-04:00, no DST
                IanaCanada::Central => -360,      // UTC-06:00, no DST
                IanaCanada::Eastern => -300,      // UTC-05:00, no DST
                IanaCanada::Mountain => -420,     // UTC-07:00, no DST
                IanaCanada::Newfoundland => -210, // UTC-03:30, no DST
                IanaCanada::Pacific => -480,      // UTC-08:00, no DST
                IanaCanada::Saskatchewan => -360, // UTC-06:00, no DST
                IanaCanada::Yukon => -420,        // UTC-07:00, no DST
            },
            IanaTimeZone::Chile(city) => match city {
                IanaChile::Continental => -240,  // UTC-04:00, no DST
                IanaChile::EasterIsland => -360, // UTC-06:00, no DST
            },
            IanaTimeZone::Mexico(city) => match city {
                IanaMexico::BajaNorte => -480, // UTC-08:00, no DST
                IanaMexico::BajaSur => -480,   // UTC-08:00, no DST
                IanaMexico::General => -420,   // UTC-07:00, no DST
            },
            IanaTimeZone::US(city) => match city {
                IanaUS::Alaska => -540,        // UTC-09:00, no DST
                IanaUS::Aleutian => -600,      // UTC-10:00, no DST
                IanaUS::Arizona => -420,       // UTC-07:00, no DST
                IanaUS::Central => -360,       // UTC-06:00, no DST
                IanaUS::EastIndiana => -300,   // UTC-05:00, no DST
                IanaUS::Eastern => -300,       // UTC-05:00, no DST
                IanaUS::Hawaii => -600,        // UTC-10:00, no DST
                IanaUS::IndianaStarke => -360, // UTC-06:00, no DST
                IanaUS::Michigan => -300,      // UTC-05:00, no DST
                IanaUS::Mountain => -420,      // UTC-07:00, no DST
                IanaUS::Pacific => -480,       // UTC-08:00, no DST
                IanaUS::Samoa => -660,         // UTC-11:00, no DST
            },
        };

        result
    }
}
