#[derive(Debug, Clone, Copy)]
pub enum IanaAfrica {
    Abidjan,
    Accra,
    AddisAbaba,
    Algiers,
    Antananarivo,
    Asmara,
    Bamako,
    Bangui,
    Banjul,
    Bissau,
    Blantyre,
    Brazzaville,
    Bujumbura,
    Ceuta,
    Cairo,
    Casablanca,
    Conakry,
    Dakar,
    DarEsSalaam,
    Djibouti,
    Douala,
    ElAaiun,
    Freetown,
    Gaborone,
    Jamestown,
    Harare,
    Juba,
    Johannesburg,
    Kampala,
    Khartoum,
    Kigali,
    Kinshasa,
    Lubumbashi,
    Lagos,
    Libreville,
    Lome,
    Luanda,
    Lusaka,
    Mamoudzou,
    Malabo,
    Maputo,
    Maseru,
    Mbabane,
    Mogadishu,
    Monrovia,
    Nairobi,
    Ndjamena,
    Niamey,
    Nouakchott,
    PortLouis,
    PortoNovo,
    SaoTome,
    Ouagadougou,
    Tripoli,
    Tunis,
    Windhoek,
}

impl IanaAfrica {
    pub fn try_from_str(value: &str) -> Option<Self> {
        match value {
            "Abidjan" => Some(Self::Abidjan),
            "Accra" => Some(Self::Accra),
            "Addis_Ababa" => Some(Self::AddisAbaba),
            "Algiers" => Some(Self::Algiers),
            "Antananarivo" => Some(Self::Antananarivo),
            "Asmara" => Some(Self::Asmara),
            "Bamako" => Some(Self::Bamako),
            "Bangui" => Some(Self::Bangui),
            "Banjul" => Some(Self::Banjul),
            "Bissau" => Some(Self::Bissau),
            "Blantyre" => Some(Self::Blantyre),
            "Brazzaville" => Some(Self::Brazzaville),
            "Bujumbura" => Some(Self::Bujumbura),
            "Ceuta" => Some(Self::Ceuta),
            "Cairo" => Some(Self::Cairo),
            "Casablanca" => Some(Self::Casablanca),
            "Conakry" => Some(Self::Conakry),
            "Dakar" => Some(Self::Dakar),
            "Dar_es_Salaam" => Some(Self::DarEsSalaam),
            "Djibouti" => Some(Self::Djibouti),
            "Douala" => Some(Self::Douala),
            "El_Aaiun" => Some(Self::ElAaiun),
            "Freetown" => Some(Self::Freetown),
            "Gaborone" => Some(Self::Gaborone),
            "Jamestown" => Some(Self::Jamestown),
            "Harare" => Some(Self::Harare),
            "Juba" => Some(Self::Juba),
            "Johannesburg" => Some(Self::Johannesburg),
            "Kampala" => Some(Self::Kampala),
            "Khartoum" => Some(Self::Khartoum),
            "Kigali" => Some(Self::Kigali),
            "Kinshasa" => Some(Self::Kinshasa),
            "Lubumbashi" => Some(Self::Lubumbashi),
            "Lagos" => Some(Self::Lagos),
            "Libreville" => Some(Self::Libreville),
            "Lome" => Some(Self::Lome),
            "Luanda" => Some(Self::Luanda),
            "Lusaka" => Some(Self::Lusaka),
            "Mamoudzou" => Some(Self::Mamoudzou),
            "Malabo" => Some(Self::Malabo),
            "Maputo" => Some(Self::Maputo),
            "Maseru" => Some(Self::Maseru),
            "Mbabane" => Some(Self::Mbabane),
            "Mogadishu" => Some(Self::Mogadishu),
            "Monrovia" => Some(Self::Monrovia),
            "Nairobi" => Some(Self::Nairobi),
            "Ndjamena" => Some(Self::Ndjamena),
            "Niamey" => Some(Self::Niamey),
            "Nouakchott" => Some(Self::Nouakchott),
            "Port_Louis" => Some(Self::PortLouis),
            "Porto-Novo" => Some(Self::PortoNovo),
            "Sao_Tome" => Some(Self::SaoTome),
            "Tripoli" => Some(Self::Tripoli),
            "Tunis" => Some(Self::Tunis),
            "Windhoek" => Some(Self::Windhoek),
            "Ouagadougou" => Some(Self::Ouagadougou),
            _ => None,
        }
    }

    pub fn as_str(&self) -> &'static str {
        match self {
            IanaAfrica::Abidjan => "Abidjan",
            IanaAfrica::Accra => "Accra",
            IanaAfrica::AddisAbaba => "Addis_Ababa",
            IanaAfrica::Algiers => "Algiers",
            IanaAfrica::Antananarivo => "Antananarivo",
            IanaAfrica::Asmara => "Asmara",
            IanaAfrica::Bamako => "Bamako",
            IanaAfrica::Bangui => "Bangui",
            IanaAfrica::Banjul => "Banjul",
            IanaAfrica::Bissau => "Bissau",
            IanaAfrica::Blantyre => "Blantyre",
            IanaAfrica::Brazzaville => "Brazzaville",
            IanaAfrica::Bujumbura => "Bujumbura",
            IanaAfrica::Ceuta => "Ceuta",
            IanaAfrica::Cairo => "Cairo",
            IanaAfrica::Casablanca => "Casablanca",
            IanaAfrica::Conakry => "Conakry",
            IanaAfrica::Dakar => "Dakar",
            IanaAfrica::DarEsSalaam => "Dar_es_Salaam",
            IanaAfrica::Djibouti => "Djibouti",
            IanaAfrica::Douala => "Douala",
            IanaAfrica::ElAaiun => "El_Aaiun",
            IanaAfrica::Freetown => "Freetown",
            IanaAfrica::Gaborone => "Gaborone",
            IanaAfrica::Jamestown => "Jamestown",
            IanaAfrica::Harare => "Harare",
            IanaAfrica::Juba => "Juba",
            IanaAfrica::Johannesburg => "Johannesburg",
            IanaAfrica::Kampala => "Kampala",
            IanaAfrica::Khartoum => "Khartoum",
            IanaAfrica::Kigali => "Kigali",
            IanaAfrica::Kinshasa => "Kinshasa",
            IanaAfrica::Lubumbashi => "Lubumbashi",
            IanaAfrica::Lagos => "Lagos",
            IanaAfrica::Libreville => "Libreville",
            IanaAfrica::Lome => "Lome",
            IanaAfrica::Luanda => "Luanda",
            IanaAfrica::Lusaka => "Lusaka",
            IanaAfrica::Mamoudzou => "Mamoudzou",
            IanaAfrica::Malabo => "Malabo",
            IanaAfrica::Maputo => "Maputo",
            IanaAfrica::Maseru => "Maseru",
            IanaAfrica::Mbabane => "Mbabane",
            IanaAfrica::Mogadishu => "Mogadishu",
            IanaAfrica::Monrovia => "Monrovia",
            IanaAfrica::Nairobi => "Nairobi",
            IanaAfrica::Ndjamena => "Ndjamena",
            IanaAfrica::Niamey => "Niamey",
            IanaAfrica::Nouakchott => "Nouakchott",
            IanaAfrica::PortLouis => "Port_Louis",
            IanaAfrica::PortoNovo => "Porto_Novo",
            IanaAfrica::SaoTome => "Sao_Tome",
            IanaAfrica::Ouagadougou => "Ouagadougou",
            IanaAfrica::Tripoli => "Tripoli",
            IanaAfrica::Tunis => "Tunis",
            IanaAfrica::Windhoek => "Windhoek",
        }
    }
}
