use crate::time_zones::iana_cities::NorthDakota;
use crate::time_zones::IanaArgentina;

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum IanaAmerica {
    Adak,
    Anchorage,
    Anguilla,
    Antigua,
    Araguaina,
    Argentina(IanaArgentina),
    Aruba,
    Atikokan,
    Asuncion,
    Atka,
    Barbados,
    Belize,
    Bogota,
    Bahia,
    BahiaBanderas,
    BlancSablon,
    Belem,
    BoaVista,
    BuenosAires,
    Boise,
    CambridgeBay,
    CampoGrande,
    Catamarca,
    Chihuahua,
    CiudadJuarez,
    CoralHarbour,
    Coyhaique,
    Creston,
    Cuiaba,
    Cordoba,
    Cancun,
    Caracas,
    Cayenne,
    Cayman,
    Chicago,
    CostaRica,
    Curacao,
    Denver,
    Dominica,
    Danmarkshavn,
    Dawson,
    DawsonCreek,
    Detroit,
    Edmonton,
    Eirunepe,
    Ensenada,
    ElSalvador,
    FortNelson,
    FortWayne,
    Fortaleza,
    GlaceBay,
    Godthab,
    GooseBay,
    GrandTurk,
    Grenada,
    Guadeloupe,
    Guatemala,
    Guayaquil,
    Guyana,

    Halifax,
    Havana,
    Hermosillo,
    Honolulu,
    Indiana(super::IanaIndiana),
    Indianapolis,
    Inuvik,
    Iqaluit,
    Juneau,
    Jamaica,
    Jujuy,
    Kentucky(super::IanaKentucky),
    Kralendijk,
    KnoxIN,
    LaPaz,
    Lima,
    LosAngeles,
    Louisville,
    Managua,
    Manaus,
    Marigot,
    Martinique,
    Montserrat,
    Mazatlan,
    Maceio,
    Matamoros,
    Mendoza,
    Menominee,
    Merida,
    Metlakatla,
    MexicoCity,
    Moncton,
    Monterrey,
    Montreal,
    Nipigon,
    Nome,
    Noronha,
    NorthDakota(super::NorthDakota),
    Miquelon,
    Montevideo,
    Nassau,
    NewYork,
    Ojinaga,
    Panama,
    Nuuk,
    Pangnirtung,
    Paramaribo,

    Phoenix,
    Pitcairn,
    PortoAcre,
    PortoVelho,
    LowerPrinces,
    PortOfSpain,
    PortAuPrince,
    PuertoRico,
    PuntaArenas,
    RainyRiver,
    RankinInlet,
    Recife,
    Resolute,
    Rosario,
    Regina,
    RioBranco,
    Tijuana,
    SantaIsabel,
    Santarem,
    SantoDomingo,
    Santiago,
    SaoPaulo,
    Scoresbysund,
    Shiprock,
    Sitka,
    StBarthelemy,
    StJohns,
    StKitts,
    StLucia,
    StThomas,
    StVincent,
    SwiftCurrent,
    Tegucigalpa,
    Thule,
    ThunderBay,
    Toronto,
    Tortola,

    Vancouver,
    Virgin,
    Whitehorse,
    Winnipeg,
    Yakutat,
    Yellowknife,
}

impl IanaAmerica {
    pub fn try_from_str(value: &str) -> Option<Self> {
        match value {
            "Adak" => Some(Self::Adak),
            "Anchorage" => Some(Self::Anchorage),
            "Anguilla" => Some(Self::Anguilla),
            "Antigua" => Some(Self::Antigua),
            "Argentina/Buenos_Aires" => Some(Self::Argentina(IanaArgentina::BuenosAires)),
            "Argentina/Catamarca" => Some(Self::Argentina(IanaArgentina::Catamarca)),
            "Argentina/ComodRivadavia" => Some(Self::Argentina(IanaArgentina::ComodRivadavia)),
            "Argentina/Cordoba" => Some(Self::Argentina(IanaArgentina::Cordoba)),
            "Argentina/Jujuy" => Some(Self::Argentina(IanaArgentina::Jujuy)),
            "Argentina/La_Rioja" => Some(Self::Argentina(IanaArgentina::LaRioja)),
            "Argentina/Mendoza" => Some(Self::Argentina(IanaArgentina::Mendoza)),
            "Argentina/Rio_Gallegos" => Some(Self::Argentina(IanaArgentina::RioGallegos)),
            "Argentina/Salta" => Some(Self::Argentina(IanaArgentina::Salta)),
            "Argentina/San_Juan" => Some(Self::Argentina(IanaArgentina::SanJuan)),
            "Argentina/San_Luis" => Some(Self::Argentina(IanaArgentina::SanLuis)),
            "Argentina/Tucuman" => Some(Self::Argentina(IanaArgentina::Tucuman)),
            "Argentina/Ushuaia" => Some(Self::Argentina(IanaArgentina::Ushuaia)),
            "Indiana/Indianapolis" => Some(Self::Indiana(super::IanaIndiana::Indianapolis)),
            "Indiana/Knox" => Some(Self::Indiana(super::IanaIndiana::Knox)),
            "Indiana/Marengo" => Some(Self::Indiana(super::IanaIndiana::Marengo)),
            "Indiana/Petersburg" => Some(Self::Indiana(super::IanaIndiana::Petersburg)),
            "Indiana/Tell_City" => Some(Self::Indiana(super::IanaIndiana::TellCity)),
            "Indiana/Vevay" => Some(Self::Indiana(super::IanaIndiana::Vevay)),
            "Indiana/Vincennes" => Some(Self::Indiana(super::IanaIndiana::Vincennes)),
            "Indiana/Winamac" => Some(Self::Indiana(super::IanaIndiana::Winamac)),
            "Kentucky/Louisville" => Some(Self::Kentucky(super::IanaKentucky::Louisville)),
            "Kentucky/Monticello" => Some(Self::Kentucky(super::IanaKentucky::Monticello)),
            "Aruba" => Some(Self::Aruba),
            "Asuncion" => Some(Self::Asuncion),
            "Barbados" => Some(Self::Barbados),
            "Belize" => Some(Self::Belize),
            "Blanc-Sablon" => Some(Self::BlancSablon),
            "Bogota" => Some(Self::Bogota),
            "Cancun" => Some(Self::Cancun),
            "Caracas" => Some(Self::Caracas),
            "Cayenne" => Some(Self::Cayenne),
            "Cayman" => Some(Self::Cayman),
            "Chicago" => Some(Self::Chicago),
            "Costa_Rica" => Some(Self::CostaRica),
            "Curacao" => Some(Self::Curacao),
            "Denver" => Some(Self::Denver),
            "Dominica" => Some(Self::Dominica),
            "Edmonton" => Some(Self::Edmonton),
            "El_Salvador" => Some(Self::ElSalvador),
            "Grand_Turk" => Some(Self::GrandTurk),
            "Grenada" => Some(Self::Grenada),
            "Guadeloupe" => Some(Self::Guadeloupe),
            "Guatemala" => Some(Self::Guatemala),
            "Guayaquil" => Some(Self::Guayaquil),
            "Guyana" => Some(Self::Guyana),
            "Glace_Bay" => Some(Self::GlaceBay),
            "Godthab" => Some(Self::Godthab),
            "Goose_Bay" => Some(Self::GooseBay),
            "Halifax" => Some(Self::Halifax),
            "Havana" => Some(Self::Havana),
            "Honolulu" => Some(Self::Honolulu),
            "Jamaica" => Some(Self::Jamaica),
            "Kralendijk" => Some(Self::Kralendijk),
            "La_Paz" => Some(Self::LaPaz),
            "Lima" => Some(Self::Lima),
            "Los_Angeles" => Some(Self::LosAngeles),
            "Managua" => Some(Self::Managua),
            "Manaus" => Some(Self::Manaus),
            "Marigot" => Some(Self::Marigot),
            "Martinique" => Some(Self::Martinique),
            "Montserrat" => Some(Self::Montserrat),
            "Mazatlan" => Some(Self::Mazatlan),
            "Mexico_City" => Some(Self::MexicoCity),
            "Noronha" => Some(Self::Noronha),
            "North_Dakota/Beulah" => Some(Self::NorthDakota(super::NorthDakota::Beulah)),
            "North_Dakota/Center" => Some(Self::NorthDakota(super::NorthDakota::Center)),
            "North_Dakota/New_Salem" => Some(Self::NorthDakota(super::NorthDakota::NewSalem)),
            "Miquelon" => Some(Self::Miquelon),
            "Montevideo" => Some(Self::Montevideo),
            "Nassau" => Some(Self::Nassau),
            "New_York" => Some(Self::NewYork),
            "Panama" => Some(Self::Panama),
            "Nuuk" => Some(Self::Nuuk),
            "Paramaribo" => Some(Self::Paramaribo),
            "Phoenix" => Some(Self::Phoenix),
            "Pitcairn" => Some(Self::Pitcairn),
            "Lower_Princes" => Some(Self::LowerPrinces),
            "Port_of_Spain" => Some(Self::PortOfSpain),
            "Port-au-Prince" => Some(Self::PortAuPrince),
            "Puerto_Rico" => Some(Self::PuertoRico),
            "Punta_Arenas" => Some(Self::PuntaArenas),
            "Regina" => Some(Self::Regina),
            "Rio_Branco" => Some(Self::RioBranco),
            "Tijuana" => Some(Self::Tijuana),
            "Santo_Domingo" => Some(Self::SantoDomingo),
            "Santiago" => Some(Self::Santiago),
            "Sao_Paulo" => Some(Self::SaoPaulo),
            "St_Barthelemy" => Some(Self::StBarthelemy),
            "St_Johns" => Some(Self::StJohns),
            "St_Kitts" => Some(Self::StKitts),
            "St_Lucia" => Some(Self::StLucia),
            "St_Thomas" => Some(Self::StThomas),
            "St_Vincent" => Some(Self::StVincent),
            "Tegucigalpa" => Some(Self::Tegucigalpa),
            "Toronto" => Some(Self::Toronto),
            "Tortola" => Some(Self::Tortola),
            "Vancouver" => Some(Self::Vancouver),
            "Winnipeg" => Some(Self::Winnipeg),
            "Araguaina" => Some(Self::Araguaina),
            "Atikokan" => Some(Self::Atikokan),
            "Atka" => Some(Self::Atka),
            "Bahia" => Some(Self::Bahia),
            "Bahia_Banderas" => Some(Self::BahiaBanderas),
            "Belem" => Some(Self::Belem),
            "Blanc_Sablon" => Some(Self::BlancSablon),
            "Boa_Vista" => Some(Self::BoaVista),
            "Buenos_Aires" => Some(Self::BuenosAires),
            "Cambridge_Bay" => Some(Self::CambridgeBay),
            "Campo_Grande" => Some(Self::CampoGrande),
            "Catamarca" => Some(Self::Catamarca),
            "Chihuahua" => Some(Self::Chihuahua),
            "Ciudad_Juarez" => Some(Self::CiudadJuarez),
            "Coral_Harbour" => Some(Self::CoralHarbour),
            "Coyhaique" => Some(Self::Coyhaique),
            "Creston" => Some(Self::Creston),
            "Cuiaba" => Some(Self::Cuiaba),
            "Cordoba" => Some(Self::Cordoba),
            "Boise" => Some(Self::Boise),
            "Danmarkshavn" => Some(Self::Danmarkshavn),
            "Dawson" => Some(Self::Dawson),
            "Dawson_Creek" => Some(Self::DawsonCreek),
            "Detroit" => Some(Self::Detroit),
            "Eirunepe" => Some(Self::Eirunepe),
            "Ensenada" => Some(Self::Ensenada),
            "Fort_Nelson" => Some(Self::FortNelson),
            "Fort_Wayne" => Some(Self::FortWayne),
            "Fortaleza" => Some(Self::Fortaleza),
            "Hermosillo" => Some(Self::Hermosillo),
            "Indianapolis" => Some(Self::Indianapolis),
            "Inuvik" => Some(Self::Inuvik),
            "Iqaluit" => Some(Self::Iqaluit),
            "Juneau" => Some(Self::Juneau),
            "Jujuy" => Some(Self::Jujuy),
            "Knox_IN" => Some(Self::KnoxIN),
            "Louisville" => Some(Self::Louisville),
            "Maceio" => Some(Self::Maceio),
            "Matamoros" => Some(Self::Matamoros),
            "Mendoza" => Some(Self::Mendoza),
            "Menominee" => Some(Self::Menominee),
            "Merida" => Some(Self::Merida),
            "Metlakatla" => Some(Self::Metlakatla),
            "Moncton" => Some(Self::Moncton),
            "Monterrey" => Some(Self::Monterrey),
            "Montreal" => Some(Self::Montreal),
            "Nipigon" => Some(Self::Nipigon),
            "Nome" => Some(Self::Nome),
            "Ojinaga" => Some(Self::Ojinaga),
            "Pangnirtung" => Some(Self::Pangnirtung),
            "Porto_Acre" => Some(Self::PortoAcre),
            "Porto_Velho" => Some(Self::PortoVelho),
            "Rainy_River" => Some(Self::RainyRiver),
            "Rankin_Inlet" => Some(Self::RankinInlet),
            "Recife" => Some(Self::Recife),
            "Resolute" => Some(Self::Resolute),
            "Rosario" => Some(Self::Rosario),
            "Santa_Isabel" => Some(Self::SantaIsabel),
            "Santarem" => Some(Self::Santarem),
            "Scoresbysund" => Some(Self::Scoresbysund),
            "Shiprock" => Some(Self::Shiprock),
            "Sitka" => Some(Self::Sitka),
            "Swift_Current" => Some(Self::SwiftCurrent),
            "Thule" => Some(Self::Thule),
            "Thunder_Bay" => Some(Self::ThunderBay),
            "Virgin" => Some(Self::Virgin),
            "Whitehorse" => Some(Self::Whitehorse),
            "Yakutat" => Some(Self::Yakutat),
            "Yellowknife" => Some(Self::Yellowknife),
            _ => None,
        }
    }

    pub fn as_str(&self) -> &str {
        match self {
            Self::Adak => "Adak",
            Self::Anchorage => "Anchorage",
            Self::Anguilla => "Anguilla",
            Self::Antigua => "Antigua",
            Self::Argentina(argentina) => match *argentina {
                IanaArgentina::BuenosAires => "Argentina/Buenos_Aires",
                IanaArgentina::Catamarca => "Argentina/Catamarca",
                IanaArgentina::ComodRivadavia => "Argentina/ComodRivadavia",
                IanaArgentina::Cordoba => "Argentina/Cordoba",
                IanaArgentina::Jujuy => "Argentina/Jujuy",
                IanaArgentina::LaRioja => "Argentina/La_Rioja",
                IanaArgentina::Mendoza => "Argentina/Mendoza",
                IanaArgentina::RioGallegos => "Argentina/Rio_Gallegos",
                IanaArgentina::Salta => "Argentina/Salta",
                IanaArgentina::SanJuan => "Argentina/San_Juan",
                IanaArgentina::SanLuis => "Argentina/San_Luis",
                IanaArgentina::Tucuman => "Argentina/Tucuman",
                IanaArgentina::Ushuaia => "Argentina/Ushuaia",
            },
            Self::Aruba => "Aruba",
            Self::Asuncion => "Asuncion",
            Self::Barbados => "Barbados",
            Self::Belize => "Belize",
            Self::Bogota => "Bogota",
            Self::Cancun => "Cancun",
            Self::Caracas => "Caracas",
            Self::Cayenne => "Cayenne",
            Self::Cayman => "Cayman",
            Self::Chicago => "Chicago",
            Self::CostaRica => "Costa_Rica",
            Self::Curacao => "Curacao",
            Self::Denver => "Denver",
            Self::Dominica => "Dominica",
            Self::Edmonton => "Edmonton",
            Self::ElSalvador => "El_Salvador",
            Self::GrandTurk => "Grand_Turk",
            Self::Grenada => "Grenada",
            Self::Guadeloupe => "Guadeloupe",
            Self::Guatemala => "Guatemala",
            Self::Guayaquil => "Guayaquil",
            Self::Guyana => "Guyana",
            Self::Halifax => "Halifax",
            Self::Havana => "Havana",
            Self::Honolulu => "Honolulu",
            Self::Indiana(indiana) => match *indiana {
                super::IanaIndiana::Indianapolis => "Indiana/Indianapolis",
                super::IanaIndiana::Knox => "Indiana/Knox",
                super::IanaIndiana::Marengo => "Indiana/Marengo",
                super::IanaIndiana::Petersburg => "Indiana/Petersburg",
                super::IanaIndiana::TellCity => "Indiana/Tell_City",
                super::IanaIndiana::Vevay => "Indiana/Vevay",
                super::IanaIndiana::Vincennes => "Indiana/Vincennes",
                super::IanaIndiana::Winamac => "Indiana/Winamac",
            },
            Self::Jamaica => "Jamaica",
            Self::Kentucky(kentucky) => match *kentucky {
                super::IanaKentucky::Louisville => "Kentucky/Louisville",
                super::IanaKentucky::Monticello => "Kentucky/Monticello",
            },
            Self::Kralendijk => "Kralendijk",
            Self::LaPaz => "La_Paz",
            Self::Lima => "Lima",
            Self::LosAngeles => "Los_Angeles",
            Self::Managua => "Managua",
            Self::Manaus => "Manaus",
            Self::Marigot => "Marigot",
            Self::Martinique => "Martinique",
            Self::Montserrat => "Montserrat",
            Self::Mazatlan => "Mazatlan",
            Self::MexicoCity => "Mexico_City",
            Self::Noronha => "Noronha",
            Self::NorthDakota(north_dakota) => match *north_dakota {
                NorthDakota::Beulah => "North_Dakota/Beulah",
                NorthDakota::Center => "North_Dakota/Center",
                NorthDakota::NewSalem => "North_Dakota/New_Salem",
            },
            Self::Miquelon => "Miquelon",
            Self::Montevideo => "Montevideo",
            Self::Nassau => "Nassau",
            Self::NewYork => "New_York",
            Self::Panama => "Panama",
            Self::Nuuk => "Nuuk",
            Self::Paramaribo => "Paramaribo",
            Self::Phoenix => "Phoenix",
            Self::Pitcairn => "Pitcairn",
            Self::LowerPrinces => "Lower_Princes",
            Self::PortOfSpain => "Port_of_Spain",
            Self::PortAuPrince => "Port-au-Prince",
            Self::PuertoRico => "Puerto_Rico",
            Self::PuntaArenas => "Punta_Arenas",
            Self::Regina => "Regina",
            Self::RioBranco => "Rio_Branco",
            Self::Tijuana => "Tijuana",
            Self::SantoDomingo => "Santo_Domingo",
            Self::Santiago => "Santiago",
            Self::SaoPaulo => "Sao_Paulo",
            Self::StBarthelemy => "St_Barthelemy",
            Self::StJohns => "St_Johns",
            Self::StKitts => "St_Kitts",
            Self::StLucia => "St_Lucia",
            Self::StThomas => "St_Thomas",
            Self::StVincent => "St_Vincent",
            Self::Tegucigalpa => "Tegucigalpa",
            Self::Toronto => "Toronto",
            Self::Tortola => "Tortola",
            Self::Vancouver => "Vancouver",
            Self::Winnipeg => "Winnipeg",
            Self::Araguaina => "Araguaina",
            Self::Atikokan => "Atikokan",
            Self::Atka => "Atka",
            Self::Bahia => "Bahia",
            Self::BahiaBanderas => "Bahia_Banderas",
            Self::Belem => "Belem",
            Self::BlancSablon => "Blanc_Sablon",
            Self::BoaVista => "Boa_Vista",
            Self::BuenosAires => "Buenos_Aires",
            Self::CambridgeBay => "Cambridge_Bay",
            Self::CampoGrande => "Campo_Grande",
            Self::Catamarca => "Catamarca",
            Self::Chihuahua => "Chihuahua",
            Self::CiudadJuarez => "Ciudad_Juarez",
            Self::CoralHarbour => "Coral_Harbour",
            Self::Coyhaique => "Coyhaique",
            Self::Creston => "Creston",
            Self::Cuiaba => "Cuiaba",
            Self::Cordoba => "Cordoba",
            Self::Boise => "Boise",
            Self::Danmarkshavn => "Danmarkshavn",
            Self::Dawson => "Dawson",
            Self::DawsonCreek => "Dawson_Creek",
            Self::Detroit => "Detroit",
            Self::Eirunepe => "Eirunepe",
            Self::Ensenada => "Ensenada",
            Self::FortNelson => "Fort_Nelson",
            Self::FortWayne => "Fort_Wayne",
            Self::Fortaleza => "Fortaleza",
            Self::Hermosillo => "Hermosillo",
            Self::GlaceBay => "Glace_Bay",
            Self::Godthab => "Godthab",
            Self::GooseBay => "Goose_Bay",
            Self::Indianapolis => "Indianapolis",
            Self::Inuvik => "Inuvik",
            Self::Iqaluit => "Iqaluit",
            Self::Juneau => "Juneau",
            Self::Jujuy => "Jujuy",
            Self::KnoxIN => "Knox_IN",
            Self::Louisville => "Louisville",
            Self::Maceio => "Maceio",
            Self::Matamoros => "Matamoros",
            Self::Mendoza => "Mendoza",
            Self::Menominee => "Menominee",
            Self::Merida => "Merida",
            Self::Metlakatla => "Metlakatla",
            Self::Moncton => "Moncton",
            Self::Monterrey => "Monterrey",
            Self::Montreal => "Montreal",
            Self::Nipigon => "Nipigon",
            Self::Nome => "Nome",
            Self::Ojinaga => "Ojinaga",
            Self::Pangnirtung => "Pangnirtung",
            Self::PortoAcre => "Porto_Acre",
            Self::PortoVelho => "Porto_Velho",
            Self::RainyRiver => "Rainy_River",
            Self::RankinInlet => "Rankin_Inlet",
            Self::Recife => "Recife",
            Self::Resolute => "Resolute",
            Self::Rosario => "Rosario",
            Self::SantaIsabel => "Santa_Isabel",
            Self::Santarem => "Santarem",
            Self::Scoresbysund => "Scoresbysund",
            Self::Shiprock => "Shiprock",
            Self::Sitka => "Sitka",
            Self::SwiftCurrent => "Swift_Current",
            Self::Thule => "Thule",
            Self::ThunderBay => "Thunder_Bay",
            Self::Virgin => "Virgin",
            Self::Whitehorse => "Whitehorse",
            Self::Yakutat => "Yakutat",
            Self::Yellowknife => "Yellowknife",
        }
    }
}
