use crate::time_zones::IanaArgentina;

#[derive(Debug, Clone, Copy)]
pub enum IanaAmerica {
    Adak,
    Anchorage,
    Anguilla,
    Antigua,
    Argentina(IanaArgentina),
    Aruba,
    Asuncion,
    Barbados,
    Belize,
    Bogota,
    Cancun,
    Caracas,
    Cayenne,
    Cayman,
    Chicago,
    CostaRica,
    Curacao,
    Denver,
    Dominica,
    Edmonton,
    ElSalvador,
    GrandTurk,
    Grenada,
    Guadeloupe,
    Guatemala,
    Guayaquil,
    Guyana,
    Halifax,
    Havana,
    Honolulu,
    Jamaica,
    Kralendijk,
    LaPaz,
    Lima,
    LosAngeles,
    Managua,
    Manaus,
    Marigot,
    Martinique,
    Montserrat,
    Mazatlan,
    MexicoCity,
    Noronha,
    Miquelon,
    Montevideo,
    Nassau,
    NewYork,
    Panama,
    Nuuk,
    Paramaribo,
    Phoenix,
    Pitcairn,
    LowerPrinces,
    PortOfSpain,
    PortAuPrince,
    PuertoRico,
    PuntaArenas,
    Regina,
    RioBranco,
    Tijuana,
    SantoDomingo,
    Santiago,
    SaoPaulo,
    StBarthelemy,
    StJohns,
    StKitts,
    StLucia,
    StThomas,
    StVincent,
    Tegucigalpa,
    Toronto,
    Tortola,
    Vancouver,
    Winnipeg,
}

impl IanaAmerica {
    pub fn try_from_str(value: &str) -> Option<Self> {
        match value {
            "Adak" => Some(Self::Adak),
            "Anchorage" => Some(Self::Anchorage),
            "Anguilla" => Some(Self::Anguilla),
            "Antigua" => Some(Self::Antigua),
            "Argentina/Buenos_Aires" => Some(Self::Argentina(IanaArgentina::BuenosAires)),
            "Argentina/Catamarca" => Some(Self::Argentina(IanaArgentina::Catamarca)),
            "Argentina/ComodRivadavia" => Some(Self::Argentina(IanaArgentina::ComodRivadavia)),
            "Argentina/Cordoba" => Some(Self::Argentina(IanaArgentina::Cordoba)),
            "Argentina/Jujuy" => Some(Self::Argentina(IanaArgentina::Jujuy)),
            "Argentina/La_Rioja" => Some(Self::Argentina(IanaArgentina::LaRioja)),
            "Argentina/Mendoza" => Some(Self::Argentina(IanaArgentina::Mendoza)),
            "Argentina/Rio_Gallegos" => Some(Self::Argentina(IanaArgentina::RioGallegos)),
            "Argentina/Salta" => Some(Self::Argentina(IanaArgentina::Salta)),
            "Argentina/San_Juan" => Some(Self::Argentina(IanaArgentina::SanJuan)),
            "Argentina/San_Luis" => Some(Self::Argentina(IanaArgentina::SanLuis)),
            "Argentina/Tucuman" => Some(Self::Argentina(IanaArgentina::Tucuman)),
            "Argentina/Ushuaia" => Some(Self::Argentina(IanaArgentina::Ushuaia)),
            "Aruba" => Some(Self::Aruba),
            "Asuncion" => Some(Self::Asuncion),
            "Barbados" => Some(Self::Barbados),
            "Belize" => Some(Self::Belize),
            "Bogota" => Some(Self::Bogota),
            "Cancun" => Some(Self::Cancun),
            "Caracas" => Some(Self::Caracas),
            "Cayenne" => Some(Self::Cayenne),
            "Cayman" => Some(Self::Cayman),
            "Chicago" => Some(Self::Chicago),
            "Costa_Rica" => Some(Self::CostaRica),
            "Curacao" => Some(Self::Curacao),
            "Denver" => Some(Self::Denver),
            "Dominica" => Some(Self::Dominica),
            "Edmonton" => Some(Self::Edmonton),
            "El_Salvador" => Some(Self::ElSalvador),
            "Grand_Turk" => Some(Self::GrandTurk),
            "Grenada" => Some(Self::Grenada),
            "Guadeloupe" => Some(Self::Guadeloupe),
            "Guatemala" => Some(Self::Guatemala),
            "Guayaquil" => Some(Self::Guayaquil),
            "Guyana" => Some(Self::Guyana),
            "Halifax" => Some(Self::Halifax),
            "Havana" => Some(Self::Havana),
            "Honolulu" => Some(Self::Honolulu),
            "Jamaica" => Some(Self::Jamaica),
            "Kralendijk" => Some(Self::Kralendijk),
            "La_Paz" => Some(Self::LaPaz),
            "Lima" => Some(Self::Lima),
            "Los_Angeles" => Some(Self::LosAngeles),
            "Managua" => Some(Self::Managua),
            "Manaus" => Some(Self::Manaus),
            "Marigot" => Some(Self::Marigot),
            "Martinique" => Some(Self::Martinique),
            "Montserrat" => Some(Self::Montserrat),
            "Mazatlan" => Some(Self::Mazatlan),
            "Mexico_City" => Some(Self::MexicoCity),
            "Noronha" => Some(Self::Noronha),
            "Miquelon" => Some(Self::Miquelon),
            "Montevideo" => Some(Self::Montevideo),
            "Nassau" => Some(Self::Nassau),
            "New_York" => Some(Self::NewYork),
            "Panama" => Some(Self::Panama),
            "Nuuk" => Some(Self::Nuuk),
            "Paramaribo" => Some(Self::Paramaribo),
            "Phoenix" => Some(Self::Phoenix),
            "Pitcairn" => Some(Self::Pitcairn),
            "Lower_Princes" => Some(Self::LowerPrinces),
            "Port_of_Spain" => Some(Self::PortOfSpain),
            "Port-au-Prince" => Some(Self::PortAuPrince),
            "Puerto_Rico" => Some(Self::PuertoRico),
            "Punta_Arenas" => Some(Self::PuntaArenas),
            "Regina" => Some(Self::Regina),
            "Rio_Branco" => Some(Self::RioBranco),
            "Tijuana" => Some(Self::Tijuana),
            "Santo_Domingo" => Some(Self::SantoDomingo),
            "Santiago" => Some(Self::Santiago),
            "Sao_Paulo" => Some(Self::SaoPaulo),
            "St_Barthelemy" => Some(Self::StBarthelemy),
            "St_Johns" => Some(Self::StJohns),
            "St_Kitts" => Some(Self::StKitts),
            "St_Lucia" => Some(Self::StLucia),
            "St_Thomas" => Some(Self::StThomas),
            "St_Vincent" => Some(Self::StVincent),
            "Tegucigalpa" => Some(Self::Tegucigalpa),
            "Toronto" => Some(Self::Toronto),
            "Tortola" => Some(Self::Tortola),
            "Vancouver" => Some(Self::Vancouver),
            "Winnipeg" => Some(Self::Winnipeg),
            _ => None,
        }
    }

    pub fn as_str(&self) -> &str {
        match self {
            Self::Adak => "Adak",
            Self::Anchorage => "Anchorage",
            Self::Anguilla => "Anguilla",
            Self::Antigua => "Antigua",
            Self::Argentina(argentina) => match *argentina {
                IanaArgentina::BuenosAires => "Argentina/Buenos_Aires",
                IanaArgentina::Catamarca => "Argentina/Catamarca",
                IanaArgentina::ComodRivadavia => "Argentina/ComodRivadavia",
                IanaArgentina::Cordoba => "Argentina/Cordoba",
                IanaArgentina::Jujuy => "Argentina/Jujuy",
                IanaArgentina::LaRioja => "Argentina/La_Rioja",
                IanaArgentina::Mendoza => "Argentina/Mendoza",
                IanaArgentina::RioGallegos => "Argentina/Rio_Gallegos",
                IanaArgentina::Salta => "Argentina/Salta",
                IanaArgentina::SanJuan => "Argentina/San_Juan",
                IanaArgentina::SanLuis => "Argentina/San_Luis",
                IanaArgentina::Tucuman => "Argentina/Tucuman",
                IanaArgentina::Ushuaia => "Argentina/Ushuaia",
            },
            Self::Aruba => "Aruba",
            Self::Asuncion => "Asuncion",
            Self::Barbados => "Barbados",
            Self::Belize => "Belize",
            Self::Bogota => "Bogota",
            Self::Cancun => "Cancun",
            Self::Caracas => "Caracas",
            Self::Cayenne => "Cayenne",
            Self::Cayman => "Cayman",
            Self::Chicago => "Chicago",
            Self::CostaRica => "Costa_Rica",
            Self::Curacao => "Curacao",
            Self::Denver => "Denver",
            Self::Dominica => "Dominica",
            Self::Edmonton => "Edmonton",
            Self::ElSalvador => "El_Salvador",
            Self::GrandTurk => "Grand_Turk",
            Self::Grenada => "Grenada",
            Self::Guadeloupe => "Guadeloupe",
            Self::Guatemala => "Guatemala",
            Self::Guayaquil => "Guayaquil",
            Self::Guyana => "Guyana",
            Self::Halifax => "Halifax",
            Self::Havana => "Havana",
            Self::Honolulu => "Honolulu",
            Self::Jamaica => "Jamaica",
            Self::Kralendijk => "Kralendijk",
            Self::LaPaz => "La_Paz",
            Self::Lima => "Lima",
            Self::LosAngeles => "Los_Angeles",
            Self::Managua => "Managua",
            Self::Manaus => "Manaus",
            Self::Marigot => "Marigot",
            Self::Martinique => "Martinique",
            Self::Montserrat => "Montserrat",
            Self::Mazatlan => "Mazatlan",
            Self::MexicoCity => "Mexico_City",
            Self::Noronha => "Noronha",
            Self::Miquelon => "Miquelon",
            Self::Montevideo => "Montevideo",
            Self::Nassau => "Nassau",
            Self::NewYork => "New_York",
            Self::Panama => "Panama",
            Self::Nuuk => "Nuuk",
            Self::Paramaribo => "Paramaribo",
            Self::Phoenix => "Phoenix",
            Self::Pitcairn => "Pitcairn",
            Self::LowerPrinces => "Lower_Princes",
            Self::PortOfSpain => "Port_of_Spain",
            Self::PortAuPrince => "Port-au-Prince",
            Self::PuertoRico => "Puerto_Rico",
            Self::PuntaArenas => "Punta_Arenas",
            Self::Regina => "Regina",
            Self::RioBranco => "Rio_Branco",
            Self::Tijuana => "Tijuana",
            Self::SantoDomingo => "Santo_Domingo",
            Self::Santiago => "Santiago",
            Self::SaoPaulo => "Sao_Paulo",
            Self::StBarthelemy => "St_Barthelemy",
            Self::StJohns => "St_Johns",
            Self::StKitts => "St_Kitts",
            Self::StLucia => "St_Lucia",
            Self::StThomas => "St_Thomas",
            Self::StVincent => "St_Vincent",
            Self::Tegucigalpa => "Tegucigalpa",
            Self::Toronto => "Toronto",
            Self::Tortola => "Tortola",
            Self::Vancouver => "Vancouver",
            Self::Winnipeg => "Winnipeg",
        }
    }
}
