#[derive(Debug, Clone, Copy)]
pub enum IanaAsia {
    Aden,
    Almaty,
    Amman,
    Ashgabat,
    Baghdad,
    Bahrain,
    Baku,
    Bangkok,
    Beirut,
    Bishkek,
    Brunei,
    Colombo,
    Damascus,
    Dhaka,
    Dubai,
    Dushanbe,
    Gaza,
    Hovd,
    Irkutsk,
    Jerusalem,
    Jakarta,
    Jayapura,
    Kabul,
    Kamchatka,
    Karachi,
    Kathmandu,
    KualaLumpur,
    Kuwait,
    Krasnoyarsk,
    Macao,
    Magadan,
    Makassar,
    Manila,
    Muscat,
    Nicosia,
    Omsk,
    Pyongyang,
    PhnomPenh,
    Qatar,
    Riyadh,
    Seoul,
    Shanghai,
    Singapore,
    Taipei,
    Tashkent,
    Tbilisi,
    Tehran,
    Thimphu,
    Vientiane,
    Tokyo,
    Ulaanbaatar,
    Urumqi,
    Vladivostok,
    Yakutsk,
    Yekaterinburg,
    Yerevan,
    Aqtau,
    Aqtobe,
    Atyrau,
    Chita,
    Choibalsan,
    Dili,
    Hebron,
    HongKong,
    Khandyga,
    Kyzylorda,
    Novokuznetsk,
    Novosibirsk,
    Pontianak,
    Qostanay,
    Qyzylorda,
    Sakhalin,
    Srednekolymsk,
    Tomsk,
    Kolkata,
    HoChiMinh,
    Yangon,
}

impl IanaAsia {
    pub fn try_from_str(value: &str) -> Option<Self> {
        match value {
            "Aden" => Some(Self::Aden),
            "Almaty" => Some(Self::Almaty),
            "Amman" => Some(Self::Amman),
            "Ashgabat" => Some(Self::Ashgabat),
            "Baghdad" => Some(Self::Baghdad),
            "Bahrain" => Some(Self::Bahrain),
            "Baku" => Some(Self::Baku),
            "Bangkok" => Some(Self::Bangkok),
            "Beirut" => Some(Self::Beirut),
            "Bishkek" => Some(Self::Bishkek),
            "Colombo" => Some(Self::Colombo),
            "Damascus" => Some(Self::Damascus),
            "Dhaka" => Some(Self::Dhaka),
            "Dubai" => Some(Self::Dubai),
            "Dushanbe" => Some(Self::Dushanbe),
            "Gaza" => Some(Self::Gaza),
            "Hovd" => Some(Self::Hovd),
            "Irkutsk" => Some(Self::Irkutsk),
            "Jerusalem" => Some(Self::Jerusalem),
            "Jakarta" => Some(Self::Jakarta),
            "Jayapura" => Some(Self::Jayapura),
            "Kabul" => Some(Self::Kabul),
            "Kamchatka" => Some(Self::Kamchatka),
            "Karachi" => Some(Self::Karachi),
            "Kathmandu" => Some(Self::Kathmandu),
            "Kuala_Lumpur" => Some(Self::KualaLumpur),
            "Kuwait" => Some(Self::Kuwait),
            "Macau" => Some(Self::Macao),
            "Magadan" => Some(Self::Magadan),
            "Makassar" => Some(Self::Makassar),
            "Manila" => Some(Self::Manila),
            "Muscat" => Some(Self::Muscat),
            "Nicosia" => Some(Self::Nicosia),
            "Omsk" => Some(Self::Omsk),
            "Pyongyang" => Some(Self::Pyongyang),
            "Qatar" => Some(Self::Qatar),
            "Riyadh" => Some(Self::Riyadh),
            "Seoul" => Some(Self::Seoul),
            "Shanghai" => Some(Self::Shanghai),
            "Singapore" => Some(Self::Singapore),
            "Taipei" => Some(Self::Taipei),
            "Tashkent" => Some(Self::Tashkent),
            "Tbilisi" => Some(Self::Tbilisi),
            "Tehran" => Some(Self::Tehran),
            "Thimphu" => Some(Self::Thimphu),
            "Vientiane" => Some(Self::Vientiane),
            "Tokyo" => Some(Self::Tokyo),
            "Ulaanbaatar" => Some(Self::Ulaanbaatar),
            "Krasnoyarsk" => Some(Self::Krasnoyarsk),
            "Urumqi" => Some(Self::Urumqi),
            "Vladivostok" => Some(Self::Vladivostok),
            "Yakutsk" => Some(Self::Yakutsk),
            "Yekaterinburg" => Some(Self::Yekaterinburg),
            "Yerevan" => Some(Self::Yerevan),
            "Aqtau" => Some(Self::Aqtau),
            "Aqtobe" => Some(Self::Aqtobe),
            "Atyrau" => Some(Self::Atyrau),
            "Chita" => Some(Self::Chita),
            "Choibalsan" => Some(Self::Choibalsan),
            "Dili" => Some(Self::Dili),
            "Hebron" => Some(Self::Hebron),
            "Hong_Kong" => Some(Self::HongKong),
            "Khandyga" => Some(Self::Khandyga),
            "Kyzylorda" => Some(Self::Kyzylorda),
            "Novokuznetsk" => Some(Self::Novokuznetsk),
            "Novosibirsk" => Some(Self::Novosibirsk),
            "Pontianak" => Some(Self::Pontianak),
            "Qostanay" => Some(Self::Qostanay),
            "Qyzylorda" => Some(Self::Qyzylorda),
            "Sakhalin" => Some(Self::Sakhalin),
            "Srednekolymsk" => Some(Self::Srednekolymsk),
            "Tomsk" => Some(Self::Tomsk),
            "Kolkata" => Some(Self::Kolkata),
            "Brunei" => Some(Self::Brunei),
            "Phnom_Penh" => Some(Self::PhnomPenh),
            "Ho_Chi_Minh" => Some(Self::HoChiMinh),
            "Yangon" => Some(Self::Yangon),
            _ => None,
        }
    }

    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Aden => "Aden",
            Self::Almaty => "Almaty",
            Self::Amman => "Amman",
            Self::Ashgabat => "Ashgabat",
            Self::Baghdad => "Baghdad",
            Self::Bahrain => "Bahrain",
            Self::Baku => "Baku",
            Self::Bangkok => "Bangkok",
            Self::Beirut => "Beirut",
            Self::Bishkek => "Bishkek",
            Self::Colombo => "Colombo",
            Self::Damascus => "Damascus",
            Self::Dhaka => "Dhaka",
            Self::Dubai => "Dubai",
            Self::Dushanbe => "Dushanbe",
            Self::Gaza => "Gaza",
            Self::Hovd => "Hovd",
            Self::Irkutsk => "Irkutsk",
            Self::Jerusalem => "Jerusalem",
            Self::Jakarta => "Jakarta",
            Self::Jayapura => "Jayapura",
            Self::Kabul => "Kabul",
            Self::Kamchatka => "Kamchatka",
            Self::Karachi => "Karachi",
            Self::Kathmandu => "Kathmandu",
            Self::KualaLumpur => "Kuala_Lumpur",
            Self::Kuwait => "Kuwait",
            Self::Krasnoyarsk => "Krasnoyarsk",
            Self::Macao => "Macau",
            Self::Magadan => "Magadan",
            Self::Makassar => "Makassar",
            Self::Manila => "Manila",
            Self::Muscat => "Muscat",
            Self::Nicosia => "Nicosia",
            Self::Omsk => "Omsk",
            Self::Pyongyang => "Pyongyang",
            Self::Qatar => "Qatar",
            Self::Riyadh => "Riyadh",
            Self::Seoul => "Seoul",
            Self::Shanghai => "Shanghai",
            Self::Singapore => "Singapore",
            Self::Taipei => "Taipei",
            Self::Tashkent => "Tashkent",
            Self::Tbilisi => "Tbilisi",
            Self::Tehran => "Tehran",
            Self::Thimphu => "Thimphu",
            Self::Vientiane => "Vientiane",
            Self::Tokyo => "Tokyo",
            Self::Ulaanbaatar => "Ulaanbaatar",
            Self::Urumqi => "Urumqi",
            Self::Vladivostok => "Vladivostok",
            Self::Yakutsk => "Yakutsk",
            Self::Yekaterinburg => "Yekaterinburg",
            Self::Yerevan => "Yerevan",
            Self::Aqtau => "Aqtau",
            Self::Aqtobe => "Aqtobe",
            Self::Atyrau => "Atyrau",
            Self::Chita => "Chita",
            Self::Choibalsan => "Choibalsan",
            Self::Dili => "Dili",
            Self::Hebron => "Hebron",
            Self::HongKong => "Hong_Kong",
            Self::Khandyga => "Khandyga",
            Self::Kyzylorda => "Kyzylorda",
            Self::Novokuznetsk => "Novokuznetsk",
            Self::Novosibirsk => "Novosibirsk",
            Self::Pontianak => "Pontianak",
            Self::Qostanay => "Qostanay",
            Self::Qyzylorda => "Qyzylorda",
            Self::Sakhalin => "Sakhalin",
            Self::Srednekolymsk => "Srednekolymsk",
            Self::Tomsk => "Tomsk",
            Self::Kolkata => "Kolkata",
            Self::Brunei => "Brunei",
            Self::PhnomPenh => "Phnom_Penh",
            Self::HoChiMinh => "Ho_Chi_Minh",
            Self::Yangon => "Yangon",
        }
    }
}
