#[derive(Debug, Clone, Copy)]
pub enum IanaEurope {
    Amsterdam,
    Andorra,
    Astrakhan,
    Athens,
    Belgrade,
    Belfast,
    Berlin,
    Bratislava,
    Brussels,
    Bucharest,
    Budapest,
    Busingen,
    Chisinau,
    Copenhagen,
    Dublin,
    Gibraltar,
    Guernsey,
    Helsinki,
    IsleOfMan,
    Istanbul,
    Jersey,
    Kaliningrad,
    Kirov,
    Kyiv,
    Lisbon,
    Ljubljana,
    London,
    Luxembourg,
    Madrid,
    Malta,
    Mariehamn,
    Minsk,
    Monaco,
    Moscow,
    Nicosia,
    Oslo,
    Paris,
    Podgorica,
    Prague,
    Riga,
    Rome,
    Samara,
    SanMarino,
    Sarajevo,
    Saratov,
    Simferopol,
    Skopje,
    Sofia,
    Stockholm,
    Tallinn,
    Tirane,
    Tiraspol,
    Ulyanovsk,
    Uzhgorod,
    Vaduz,
    Vatican,
    Vienna,
    Vilnius,
    Volgograd,
    Warsaw,
    Zagreb,
    Zaporozhye,
    Zurich,
}

impl IanaEurope {
    pub fn try_from_str(value: &str) -> Option<Self> {
        match value {
            "Amsterdam" => Some(Self::Amsterdam),
            "Andorra" => Some(Self::Andorra),
            "Astrakhan" => Some(Self::Astrakhan),
            "Athens" => Some(Self::Athens),
            "Belgrade" => Some(Self::Belgrade),
            "Belfast" => Some(Self::Belfast),
            "Berlin" => Some(Self::Berlin),
            "Bratislava" => Some(Self::Bratislava),
            "Brussels" => Some(Self::Brussels),
            "Bucharest" => Some(Self::Bucharest),
            "Budapest" => Some(Self::Budapest),
            "Busingen" => Some(Self::Busingen),
            "Chisinau" => Some(Self::Chisinau),
            "Copenhagen" => Some(Self::Copenhagen),
            "Dublin" => Some(Self::Dublin),
            "Gibraltar" => Some(Self::Gibraltar),
            "Guernsey" => Some(Self::Guernsey),
            "Helsinki" => Some(Self::Helsinki),
            "Isle_of_Man" => Some(Self::IsleOfMan),
            "Istanbul" => Some(Self::Istanbul),
            "Jersey" => Some(Self::Jersey),
            "Kaliningrad" => Some(Self::Kaliningrad),
            "Kirov" => Some(Self::Kirov),
            "Kyiv" => Some(Self::Kyiv),
            "Kiev" => Some(Self::Kyiv),
            "Lisbon" => Some(Self::Lisbon),
            "Ljubljana" => Some(Self::Ljubljana),
            "London" => Some(Self::London),
            "Luxembourg" => Some(Self::Luxembourg),
            "Madrid" => Some(Self::Madrid),
            "Malta" => Some(Self::Malta),
            "Mariehamn" => Some(Self::Mariehamn),
            "Minsk" => Some(Self::Minsk),
            "Monaco" => Some(Self::Monaco),
            "Moscow" => Some(Self::Moscow),
            "Nicosia" => Some(Self::Nicosia),
            "Oslo" => Some(Self::Oslo),
            "Paris" => Some(Self::Paris),
            "Podgorica" => Some(Self::Podgorica),
            "Prague" => Some(Self::Prague),
            "Riga" => Some(Self::Riga),
            "Rome" => Some(Self::Rome),
            "Samara" => Some(Self::Samara),
            "San_Marino" => Some(Self::SanMarino),
            "Sarajevo" => Some(Self::Sarajevo),
            "Saratov" => Some(Self::Saratov),
            "Simferopol" => Some(Self::Simferopol),
            "Skopje" => Some(Self::Skopje),
            "Sofia" => Some(Self::Sofia),
            "Stockholm" => Some(Self::Stockholm),
            "Tallinn" => Some(Self::Tallinn),
            "Tirane" => Some(Self::Tirane),
            "Ulyanovsk" => Some(Self::Ulyanovsk),
            "Vaduz" => Some(Self::Vaduz),
            "Vatican" => Some(Self::Vatican),
            "Vienna" => Some(Self::Vienna),
            "Vilnius" => Some(Self::Vilnius),
            "Volgograd" => Some(Self::Volgograd),
            "Warsaw" => Some(Self::Warsaw),
            "Zagreb" => Some(Self::Zagreb),
            "Zurich" => Some(Self::Zurich),
            "Tiraspol" => Some(Self::Tiraspol),
            "Uzhgorod" => Some(Self::Uzhgorod),
            "Zaporozhye" => Some(Self::Zaporozhye),
            _ => None,
        }
    }

    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Amsterdam => "Amsterdam",
            Self::Andorra => "Andorra",
            Self::Astrakhan => "Astrakhan",
            Self::Athens => "Athens",
            Self::Belgrade => "Belgrade",
            Self::Belfast => "Belfast",
            Self::Berlin => "Berlin",
            Self::Bratislava => "Bratislava",
            Self::Brussels => "Brussels",
            Self::Bucharest => "Bucharest",
            Self::Budapest => "Budapest",
            Self::Busingen => "Busingen",
            Self::Chisinau => "Chisinau",
            Self::Copenhagen => "Copenhagen",
            Self::Dublin => "Dublin",
            Self::Gibraltar => "Gibraltar",
            Self::Guernsey => "Guernsey",
            Self::Helsinki => "Helsinki",
            Self::IsleOfMan => "Isle_of_Man",
            Self::Istanbul => "Istanbul",
            Self::Jersey => "Jersey",
            Self::Kaliningrad => "Kaliningrad",
            Self::Kirov => "Kirov",
            Self::Kyiv => "Kyiv",
            Self::Lisbon => "Lisbon",
            Self::Ljubljana => "Ljubljana",
            Self::London => "London",
            Self::Luxembourg => "Luxembourg",
            Self::Madrid => "Madrid",
            Self::Malta => "Malta",
            Self::Mariehamn => "Mariehamn",
            Self::Minsk => "Minsk",
            Self::Monaco => "Monaco",
            Self::Moscow => "Moscow",
            Self::Nicosia => "Nicosia",
            Self::Oslo => "Oslo",
            Self::Paris => "Paris",
            Self::Podgorica => "Podgorica",
            Self::Prague => "Prague",
            Self::Riga => "Riga",
            Self::Rome => "Rome",
            Self::Samara => "Samara",
            Self::SanMarino => "San_Marino",
            Self::Sarajevo => "Sarajevo",
            Self::Saratov => "Saratov",
            Self::Simferopol => "Simferopol",
            Self::Skopje => "Skopje",
            Self::Sofia => "Sofia",
            Self::Stockholm => "Stockholm",
            Self::Tallinn => "Tallinn",
            Self::Tirane => "Tirane",
            Self::Tiraspol => "Tiraspol",
            Self::Ulyanovsk => "Ulyanovsk",
            Self::Uzhgorod => "Uzhgorod",
            Self::Vaduz => "Vaduz",
            Self::Vatican => "Vatican",
            Self::Vienna => "Vienna",
            Self::Vilnius => "Vilnius",
            Self::Volgograd => "Volgograd",
            Self::Warsaw => "Warsaw",
            Self::Zagreb => "Zagreb",
            Self::Zaporozhye => "Zaporozhye",
            Self::Zurich => "Zurich",
        }
    }
}
