#[derive(Debug, Clone, Copy)]
pub enum IanaPacific {
    Apia,
    Auckland,
    Baker,
    Bougainville,
    Chatham,
    Chuuk,
    Easter,
    Efate,
    Enderbury,
    Fakaofo,
    Fiji,
    Funafuti,
    Galapagos,
    Gambier,
    Guam,
    Guadalcanal,
    Honolulu,
    Johnston,
    Kanton,
    Kiritimati,
    Kosrae,
    Kwajalein,
    Majuro,
    Marquesas,
    Midway,
    Nauru,
    Niue,
    Norfolk,
    Noumea,
    Palau,
    Pitcairn,
    Pohnpei,
    PortMoresby,
    Rarotonga,
    PagoPago,
    Samoa,
    Saipan,
    Tahiti,
    Tarawa,
    Tongatapu,
    Truk,
    Wallis,
    Wake,
    Yap,
}

impl IanaPacific {
    pub fn try_from_str(value: &str) -> Option<Self> {
        match value {
            "Apia" => Some(Self::Apia),
            "Auckland" => Some(Self::Auckland),
            "Baker" => Some(Self::Baker),
            "Bougainville" => Some(Self::Bougainville),
            "Chatham" => Some(Self::Chatham),
            "Chuuk" => Some(Self::Chuuk),
            "Easter" => Some(Self::Easter),
            "Efate" => Some(Self::Efate),
            "Enderbury" => Some(Self::Enderbury),
            "Fakaofo" => Some(Self::Fakaofo),

            "Fiji" => Some(Self::Fiji),
            "Funafuti" => Some(Self::Funafuti),
            "Galapagos" => Some(Self::Galapagos),
            "Gambier" => Some(Self::Gambier),
            "Guam" => Some(Self::Guam),
            "Guadalcanal" => Some(Self::Guadalcanal),
            "Honolulu" => Some(Self::Honolulu),
            "Johnston" => Some(Self::Johnston),
            "Kanton" => Some(Self::Kanton),
            "Kiritimati" => Some(Self::Kiritimati),
            "Kosrae" => Some(Self::Kosrae),
            "Kwajalein" => Some(Self::Kwajalein),
            "Majuro" => Some(Self::Majuro),
            "Marquesas" => Some(Self::Marquesas),
            "Midway" => Some(Self::Midway),
            "Nauru" => Some(Self::Nauru),
            "Niue" => Some(Self::Niue),
            "Norfolk" => Some(Self::Norfolk),
            "Noumea" => Some(Self::Noumea),
            "Palau" => Some(Self::Palau),
            "Pitcairn" => Some(Self::Pitcairn),
            "Pohnpei" => Some(Self::Pohnpei),
            "Ponape" => Some(Self::Pohnpei),
            "Port_Moresby" => Some(Self::PortMoresby),
            "Rarotonga" => Some(Self::Rarotonga),
            "Saipan" => Some(Self::Saipan),
            "Tahiti" => Some(Self::Tahiti),
            "Tarawa" => Some(Self::Tarawa),
            "Tongatapu" => Some(Self::Tongatapu),
            "Truk" => Some(Self::Truk),
            "Wallis" => Some(Self::Wallis),
            "Wake" => Some(Self::Wake),
            "Pago_Pago" => Some(Self::PagoPago),
            "Samoa" => Some(Self::Samoa),
            "Yap" => Some(Self::Yap),
            _ => None,
        }
    }

    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Apia => "Apia",
            Self::Auckland => "Auckland",
            Self::Baker => "Baker",
            Self::Bougainville => "Bougainville",
            Self::Chatham => "Chatham",
            Self::Chuuk => "Chuuk",
            Self::Easter => "Easter",
            Self::Efate => "Efate",
            Self::Enderbury => "Enderbury",
            Self::Fakaofo => "Fakaofo",
            Self::Fiji => "Fiji",
            Self::Funafuti => "Funafuti",
            Self::Galapagos => "Galapagos",
            Self::Gambier => "Gambier",
            Self::Guam => "Guam",
            Self::Guadalcanal => "Guadalcanal",
            Self::Honolulu => "Honolulu",
            Self::Johnston => "Johnston",
            Self::Kanton => "Kanton",
            Self::Kiritimati => "Kiritimati",

            Self::Kosrae => "Kosrae",
            Self::Kwajalein => "Kwajalein",
            Self::Majuro => "Majuro",
            Self::Marquesas => "Marquesas",
            Self::Midway => "Midway",
            Self::Nauru => "Nauru",
            Self::Niue => "Niue",
            Self::Norfolk => "Norfolk",
            Self::Noumea => "Noumea",
            Self::Palau => "Palau",
            Self::Pitcairn => "Pitcairn",
            Self::Pohnpei => "Pohnpei",
            Self::PortMoresby => "Port_Moresby",
            Self::Rarotonga => "Rarotonga",
            Self::PagoPago => "Pago_Pago",
            Self::Samoa => "Samoa",
            Self::Saipan => "Saipan",
            Self::Tahiti => "Tahiti",
            Self::Tarawa => "Tarawa",
            Self::Tongatapu => "Tongatapu",
            Self::Truk => "Truk",
            Self::Wallis => "Wallis",
            Self::Wake => "Wake",
            Self::Yap => "Yap",
        }
    }
}
