#[derive(Debug, Clone, Copy)]
pub enum IanaPacific {
    Apia,
    Auckland,
    Baker,
    Efate,
    Fakaofo,
    Fiji,
    Funafuti,
    Guam,
    Guadalcanal,
    Honolulu,
    Kiritimati,
    Majuro,
    Midway,
    Nauru,
    Niue,
    Norfolk,
    Noumea,
    Palau,
    Pitcairn,
    Pohnpei,
    PortMoresby,
    Rarotonga,
    PagoPago,
    Saipan,
    Tahiti,
    Tarawa,
    Tongatapu,
    Wallis,
}

impl IanaPacific {
    pub fn try_from_str(value: &str) -> Option<Self> {
        match value {
            "Apia" => Some(Self::Apia),
            "Auckland" => Some(Self::Auckland),
            "Baker" => Some(Self::Baker),
            "Efate" => Some(Self::Efate),
            "Fakaofo" => Some(Self::Fakaofo),
            "Fiji" => Some(Self::Fiji),
            "Funafuti" => Some(Self::Funafuti),
            "Guam" => Some(Self::Guam),
            "Guadalcanal" => Some(Self::Guadalcanal),
            "Honolulu" => Some(Self::Honolulu),
            "Kiritimati" => Some(Self::Kiritimati),
            "Majuro" => Some(Self::Majuro),
            "Midway" => Some(Self::Midway),
            "Nauru" => Some(Self::Nauru),
            "Niue" => Some(Self::Niue),
            "Norfolk" => Some(Self::Norfolk),
            "Noumea" => Some(Self::Noumea),
            "Palau" => Some(Self::Palau),
            "Pitcairn" => Some(Self::Pitcairn),
            "Pohnpei" => Some(Self::Pohnpei),
            "Port_Moresby" => Some(Self::PortMoresby),
            "Rarotonga" => Some(Self::Rarotonga),
            "Saipan" => Some(Self::Saipan),
            "Tahiti" => Some(Self::Tahiti),
            "Tarawa" => Some(Self::Tarawa),
            "Tongatapu" => Some(Self::Tongatapu),
            "Wallis" => Some(Self::Wallis),
            "Pago_Pago" => Some(Self::PagoPago),
            _ => None,
        }
    }

    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Apia => "Apia",
            Self::Auckland => "Auckland",
            Self::Baker => "Baker",
            Self::Efate => "Efate",
            Self::Fakaofo => "Fakaofo",
            Self::Fiji => "Fiji",
            Self::Funafuti => "Funafuti",
            Self::Guam => "Guam",
            Self::Guadalcanal => "Guadalcanal",
            Self::Honolulu => "Honolulu",
            Self::Kiritimati => "Kiritimati",
            Self::Majuro => "Majuro",
            Self::Midway => "Midway",
            Self::Nauru => "Nauru",
            Self::Niue => "Niue",
            Self::Norfolk => "Norfolk",
            Self::Noumea => "Noumea",
            Self::Palau => "Palau",
            Self::Pitcairn => "Pitcairn",
            Self::Pohnpei => "Pohnpei",
            Self::PortMoresby => "Port_Moresby",
            Self::Rarotonga => "Rarotonga",
            Self::Saipan => "Saipan",
            Self::Tahiti => "Tahiti",
            Self::Tarawa => "Tarawa",
            Self::Tongatapu => "Tongatapu",
            Self::Wallis => "Wallis",
            Self::PagoPago => "Pago_Pago",
        }
    }
}
